project:
  type: website
  output-dir: docs
  resources: 
    - robots.txt

website:
  title: "SistemaBochi"
  favicon: baeducacion.png
  
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: entregas_mobiliario.qmd
        text: Mobiliario

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

