project:
  type: website
  output-dir: docs

website:
  title: "SistemaBochi"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: entregas_mobiliario.qmd
        text: Mobiliario

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

