---
title: "Últimas entregas de mobiliario"
---

<!-- data/consolidado_entregas_08-08-23.csv -->

*Última actualización:* 13-09-23

------------------------------------------------------------------------

```{r packages, warning=FALSE,error=FALSE,message=FALSE,include=FALSE}

packages <- c("DT","readr","dplyr")
# Install packages not yet installed
installed_packages <- packages %in% rownames(installed.packages())
if (any(installed_packages == FALSE)) {
  install.packages(packages[!installed_packages])
}

invisible(lapply(packages, library, character.only = TRUE))

```

```{r read, warning=FALSE,error=FALSE,message=FALSE,include=FALSE}
base_entregas <- read_csv("data/tabla_entregas_13-09-23.csv") %>% 
  # select(cue,establecimiento,direccion,muebles,cantidad)
  glimpse()

tabla_entregas <- DT::datatable(base_entregas, 
                       filter = "top", 
                       rownames = FALSE,
                       escape = FALSE, 
                       class = 'cell-border stripe',
                       options = list(pageLength = 50, autoWidth = TRUE)
                       )


```


```{r show, echo=FALSE}
tabla_entregas
```
