---
title: Sistema de Consulta Escolar 1.0
format: 
  html:
    page-layout: full
---

Aplicación de consulta de la SSGEFYAR.

Busque por dirección, nombre, número de escuela, y/o distrito para acceder a los detalles.

*Última actualización:* Infra: 05-12, Mobiliario: 05-12, Mantenimiento: 05-12, Seguridad: 10-10.

------------------------------------------------------------------------

```{r packages, warning=FALSE,error=FALSE,message=FALSE,include=FALSE}

packages <- c("DT","readr","dplyr")
# Install packages not yet installed
installed_packages <- packages %in% rownames(installed.packages())
if (any(installed_packages == FALSE)) {
  install.packages(packages[!installed_packages])
}

invisible(lapply(packages, library, character.only = TRUE))

```

```{r read, warning=FALSE,error=FALSE,message=FALSE,include=FALSE}
raw <- read_csv("data/base_completa_link_v6.csv") %>% 
  # glimpse()
  select(Domicilio, Establecimiento, Nº, DE)

tabla <- DT::datatable(raw, 
                       filter = "top", 
                       rownames = FALSE,
                       escape = FALSE, 
                       class = 'cell-border stripe',
                       options = list(pageLength = 50, autoWidth = TRUE)
                       )


```

```{r show, echo=FALSE}
tabla
```
