---
title: 'AYACUCHO 1849'
subtitle: 'JIN C (EPCJC 21/01°) - EPC N° 21 ANGEL GALLARDO'
---

#
## Infraestructura

* Instalacion electrica 
    + Mejora Edilicia - En Proyecto 
    + Inicio de obra: NA 


* Instalación eléctrica 
    + Mejora Edilicia - Finalizado 
    + Finalizada el 03/03/2023 






## Mantenimiento

*  (2023) Electricidad 
    + Colocacion de 8 ventiladores de pared

*  (2022) Albañileria / Pintura 
    + Pintura de Paredes y retiro de placas.

*  (2022) Calefaccion y Refrigeracion 
    + Cambio de 3 estufas

*  (2022) Carpinterías 
    + Colocacion de Films Polarizados

*  (2022) Gas 
    + Cambio de termotanque de casera. La supe

*  (2022) Sanitarias 
    + Canalizacion de desague de mingitorios

*  (2021) Calefaccion y Refrigeracion 
    + Reparación de estufas

*  (2021) Cubiertas / Impermeabilizaciones 
    + cambio de chapas en techo de comedor

*  (2021) Medios de elevación 
    + Adecuacion de ascensor





## Mobiliario

*  (2022) : Armario 2, Banco largo comedor 112, Mesa inicial 5, Mesa usos múltiples 56, Pizarrón 7, Silla escolar 30 

*  (2021) : Armario 4, Escritorio 4, Mesa pupitre doble 60, Silla escolar 124 



