---
title: 'VALDENEGRO 3525'
subtitle: 'EPC N° 12 ESPAÑA - JIN C (EPCJC 12/15°) [S] - PI VALDENEGRO'
---

#
## Infraestructura

* Intervención completa de fachadas de valdenegro, incluidas las del contrafrente sobre la calle miller y las caras interiores no contempladas en obra de ampliación nes, patios, reparación de humedades en mamposterías, acondicionamiento de patios, reparación de carpinterías, acondicionamiento de sanitarios de docentes, acondicionamiento de instalación de provisión de agua y reparacion de tanques ( sistema integral para ambas escuelas), revisión de cubiertas e instalación pluvial.
En media pintura general de los sectores requeridos que no hayan sido intervenidos por la obra de ampliación ni por sdf ejecutada por dgmesc.
En primaria pintura integral, acondicionamiento de instalación eléctrica y accesibilidad plena.
 
    + mejora edilicia - Planificado 
    + Inicio de obra: 15/04/2024 
    + Plan de obras 2024 - 2027 


* Obra rescindida: trabajos de ampliación edilicia, medios de salida y pintura integral de fachadas 
    + mejora edilicia - Finalizado 
    + Finalizada el 17/05/2022 
    + Plan de obras 2021 - 2023 






## Mobiliario

*  (2023) : Escritorio 2, Mesa inicial 10, Silla escolar 60 

*  (2022) : Banco largo comedor 50, Mesa usos múltiples 25 

*  (2021) : Armario 14, Escritorio 3, Mesa inicial 10, Mesa pupitre doble 45, Piso antigolpe para juegos 64, Silla escolar 153, Varios 40 



