---
title: 'LUIS VIALE 1046'
subtitle: 'EPC N° 19 GALICIA'
---

#
## Infraestructura

* Demolicion completa de contruccion en patio y trabajos de retiro de asbesto, accesibilidad  basica, cambio de carpinterias y cubierta  de galeria y paso que da al patio, nuevo nucleo sanitario en donde funcionaba la sala de maestro y sanitario adjunto. demolicion de sanitarios en sum. demolicion de parrilla y armado de lugar para gimnacio.  puesta en valor de sanitarios existentes y sala de auxiliares. instalacion sanitaria (cambio de tanque bombeo) y adecuacion de instalacion electrica. refuncionalizar casa del casero: cambio de cielorraso, puesta en valor del santario, cambio de carpinterias. completamiento de medianera y arreglo de muro existente. 
    + mejora edilicia - Licitación 
    + Inicio de obra: 07/02/2024 






## Mantenimiento

*  (2023) Carpinterías 
    + Adecuación instalación gas

*  (2023) Gas 
    + Cajones de Durlock

*  (2023) Sanitarias 
    + Arreglo Tanque de Agua y tablero electr.

*  (2022) Cubiertas / Impermeabilizaciones 
    + Cambio de cubierta  desagües pluviales

*  (2022) Electricidad 
    + Aumento de potencia, Adicional aumento de potencia, “Instalación de 3 de Aire Acondic

*  (2022) Incendio 
    + Proveer extintores según plano

*  (2021) Electricidad 
    + Instalacion equipos purificadores, Adecuación eléctrica de la válv solenoid





## Mobiliario

*  (2023) : NA 1 

*  (2021) : Banco largo comedor 24, Mesa usos múltiples 12 



