---
title: 'CAFAYATE 5115'
subtitle: 'JIN B (EPCJC 01/21°) [S] - EPC N° 01 CONCEJAL ALBERTO SALVATORI - CENS N° 67 - PI LOS GRILLITOS'
---

#


## Mobiliario

*  (2021) : Banco largo comedor 116, Mesa inicial 20, Mesa usos múltiples 58, Pizarrón 10, Silla escolar 120 





## Mantenimiento

*  (2023) Albañileria / Pintura 
    + Reparacion de patio jardin

*  (2023) Electricidad 
    + Seguridad para aula laboratorio pa, Reposición de 4 de pared de 20

*  (2023) Incendio 
    + Reposición de manguera y lanza de cobre

*  (2023) Medios de elevación 
    + Reparar puerta ascensor vandalismo

*  (2023) Sanitarias 
    + Reposición de dos inodoros, Realización de 2 cámaras de inspección, Cañería de agua alimentación jardín

*  (2022) Carpinterías 
    + Rep. herrajes cerraduras - Vandalismo, Reposición de cerradura por vandalismo, Recambio tapas de tanque

*  (2022) Electricidad 
    + Recambio de 5 Ventidaores de pared

*  (2022) Sanitarias 
    + Reparacion caño de agua, Cambio de inodoro por vandalismo

*  (2021) Carpinterías 
    + Reponer cerradura en puerta patio PA x v

*  (2021) Cubiertas / Impermeabilizaciones 
    + Reparar techo de chapa por filtraciones

*  (2021) Medios de elevación 
    + reacondicionamiento de ascensor



