---
title: 'AVDA. RIVADAVIA 3577'
subtitle: 'Sup Media Region III - COLEGIO N° 03 MARIANO MORENO - IFTS N° 28'
---

#
## Infraestructura

* Refuncionalización de sanitarios- restauracion de fachadas interiores y exteriores- cielorrasos ( cambio y/o restauración)- solados- restauracion de mansarda y vitreaux- instalacion electrica completa- adecuación de instalacion sanitaria. incendio y gas- y adecuación de subsuelo ( tratamiento de humedad) 
    + mejora edilicia - En Proyecto 
    + Inicio de obra: Sin fecha de inicio 






## Mantenimiento

*  (2023) Albañileria / Pintura 
    + Readecuacion aulas para SDF., Reemplazo de matafuegos

*  (2023) Carpinterías 
    + Adicional de 6 cerraduras para aulas

*  (2023) Cubiertas / Impermeabilizaciones 
    + IMPERMEABILIZACIÓN DE AZOTEA

*  (2023) Electricidad 
    + Prov. Inst. sistema Espacio Seguro, Reemplazar ventiladores de techo

*  (2022) Incendio 
    + Provisión de 8 matafuegos 1 ABC 5 kg

*  (2021) Gas 
    + Acond. instalacion de gas buffet

*  (2021) Incendio 
    + Colocación de matafuego en subsuelo





## Mobiliario

*  (2023) : Escritorio 5, Mesa pupitre doble 75, Pizarrón 5, Silla escolar 155 





## Seguridad

*  Espacios seguros: 1 - Estado: En ejecución 
    + Guardia física: NO



