---
title: 'CAÑADA DE GOMEZ 3850'
subtitle: 'EEM N° 02/20° - JM N° 05/20° (A) - CAIYJ CLUB MATADEROS - IFTS N° 02'
---

#
## Infraestructura

* Incorporacion de dos aulas de steel frame y nucleo sanitarios. traslado de mastil. 
    + mejora edilicia - En Obra 
    + Inicio de obra: Sin fecha de inicio - Avance: NA - Fecha de finalización: - 






## Mantenimiento

*  (2023) Electricidad 
    + Colocación de luces de emergencia, Espacio digital y oficina de alumnos, Provision de 15 Ventiladores

*  (2023) Gas 
    + reemplazo de regulador de gas

*  (2023) Medios de elevación 
    + Reparar ascensor

*  (2022) Albañileria / Pintura 
    + Prov. coloc. placa cielorraso, Ejecución de dos aula futuro para 5to

*  (2022) Carpinterías 
    + Reemplazo de 4 puertas antipanico

*  (2022) Cubiertas / Impermeabilizaciones 
    + Reemplazo de Termotanque Electrico

*  (2022) Gas 
    + Readecuar instalación de gas

*  (2022) Medios de elevación 
    + Reparación de Ascensor

*  (2022) Sanitarias 
    + Provisión interna de agua en aula modula

*  (2021) Albañileria / Pintura 
    + Cotizacion de dos aulas SDF 4to Año Se d

*  (2021) Cubiertas / Impermeabilizaciones 
    + IMPERMEABILIZACION DE TERRAZA

*  (2021) Electricidad 
    + Secundarias Futuro 2020, Colocar 3 ventiladores de pared, Tendido electrico alimentacion de Horno, Inst. Horno electrico en cocina

*  (2021) Gas 
    + Puesta en condiciones instalacion de gas, Provision y colocacion de termotanque, Prov y coloc  termotanque en cocina.

*  (2021) Sanitarias 
    + Ejecucion de descarga mingitorio





## Mobiliario

*  (2023) : Escritorio 2, Mesa pupitre doble 30, Pizarrón 2, Silla escolar 62, NA 1 

*  (2022) : Escritorio 2, Mesa pupitre doble 30, Pizarrón 2, Silla escolar 62 

*  (2021) : Escritorio 3, Mesa pupitre doble 45, Pizarrón 3, Silla escolar 93 





## Seguridad

*  Espacios seguros: 5 - Estado: Suspendida ejecución 
    + Guardia física: NO



