---
title: 'GOLETA SANTA CRUZ 6997 - GOLETA SANTA CRUZ 6999'
subtitle: 'ESC. INTEGRAL INTERDISCIPLINARIA N° 20 ALICIA MOREAU DE JUSTO - EPA N° 21 SOLDADO DE MALVINAS - EPC N° 21 SOLDADO DE MALVINAS - JIC N° 10/20°'
---

#
## Infraestructura

* Carpinterías, cubierta y pintura en areas significativas 
    + Mejora Edilicia - Licitación 
    + Inicio de obra: NA 






## Mantenimiento

*  (2023) Electricidad 
    + Provision y colocación de 15 ventiladore

*  (2023) Sanitarias 
    + Cambio de tapas de inspeccion y limpieza

*  (2022) Albañileria / Pintura 
    + Realizar muro exterior en mamposteria

*  (2022) Carpinterías 
    + Puerta de aula taller de 1er PISO, Cambio de cerradura cocina vandalismo, Provisión y colocación puerta antipanico, Provisión de cerradura por vandalismo

*  (2022) Sanitarias 
    + Reemplazo de tanque, Prov. Coloc tapas de inodoros baños, Provision de un inodoro vandalizado B°al, Cambio de cañeria por termofucion aerea, Provision y colocación de inodoro por va

*  (2021) Carpinterías 
    + Colocacion de puerta antipanico, 2 cerradura vandalizada en el interior, Cerraduras vandalizadas exterior

*  (2021) Gas 
    + adecuacion instalacion gas, Prov,coloc termotanque 120lts cocina, Prov y coloc calefon casa casera

*  (2021) Sanitarias 
    + Termotanque eléctrico en casa casera





## Mobiliario

*  (2021) : Escritorio 4, Mesa pupitre doble 60, Silla escolar 124 



