---
title: 'AVDA. DON PEDRO DE MENDOZA 1835 - GRAL. GREGORIO ARAOZ DE LAMADRID 648'
subtitle: 'Museo de Bellas Artes de Artistas Argentinos Benito Quinquela Martin - EPC N° 09 BENITO QUINQUELA MARTIN - CENS N° 32 - CENOF CENTRO MUSEO QUINQUELA MARTIN - JII N° 01/04° BENITO QUINQUELA MARTIN'
---

#
## Infraestructura

* Acondicionamiento  de cubierta, instalacion sanitario, electrica e incendio. Arreglo de revoques menores en aulas.  Adecuacion pintura interior de areas significantes  y patio. 
    + Mejora Edilicia - En Proyecto 
    + Inicio de obra: 1/8/2024 


* NA 
    + Obra Nueva - Finalizado 
    + Finalizada el Esperando corrección de fecha 






## Mantenimiento

*  (2023) Calefaccion y Refrigeracion 
    + Reparar equipo de aire acondicionado

*  (2023) Electricidad 
    + Instalación de espacios seguro, readecuación instalación de gas

*  (2022) Albañileria / Pintura 
    + Pintura de cielorrasos/techos

*  (2022) Calefaccion y Refrigeracion 
    + Reemplazo de compresor en corto, Abono mensual mantenimiento AA, Instalación de humectadores, Limpiar filtros de aire acondicionado, Proveer y colocar humectadores

*  (2022) Carpinterías 
    + Proveer y colocar dos escaleras

*  (2022) Cubiertas / Impermeabilizaciones 
    + Correr la descarga pluvial

*  (2022) Electricidad 
    + Colocación de luces en hall

*  (2022) Otros Servicios 
    + Prov. coloc. red anti palomas

*  (2021) Albañileria / Pintura 
    + Pintura de rejas 2da etapa, Pintura rejas 3era etapa, Reparacion de paredes, pintura de muros

*  (2021) Calefaccion y Refrigeracion 
    + reposicion bombas calderas





## Mobiliario

*  (2022) : Armario 24, Biblioteca 12, Escritorio 8, Juego de patio 1, Mesa inicial 30, Piso antigolpe para juegos 60, Pizarrón 16, Silla escolar 410, Varios 8 

*  (2021) : Armario 5, Mesa inicial 20, Mesa pupitre doble 30, Mesa usos múltiples 10, Pizarrón 2, Silla escolar 150 



