---
title: 'NICOLAS DESCALZI 5425'
subtitle: 'EPC N° 06 REPUBLICA DE LA INDIA - JII N° 02/21°'
---

#
## Infraestructura

* Plan mejora patio+ cielorraso+carpinteria+ inst gas y calefaccion+ sanitario+ cubierta + reparacion revoques y pintura en areas significativas 
    + Mejora Edilicia - Planificado 
    + Inicio de obra: Sin fecha de inicio 






## Mantenimiento

*  (2023) Calefaccion y Refrigeracion 
    + Reparación de sistema de calefacción.

*  (2023) Electricidad 
    + Protocolo Espacio seguro

*  (2022) Albañileria / Pintura 
    + Prov. Inst.  de piso antigolpe

*  (2022) Calefaccion y Refrigeracion 
    + Reparación de bombas de recirculación

*  (2022) Incendio 
    + Reposición de mangueras en hidrantes

*  (2021) Albañileria / Pintura 
    + Reparar solado patio posterior

*  (2021) Medios de elevación 
    + puesta en norma del ascensor





## Mobiliario

*  (2023) : Mesa inicial 17, Mesa pupitre doble 30, Pizarrón 4, Silla escolar 168 





## Seguridad

*  Espacios seguros: 1 - Estado: Finalizado 
    + Guardia física: NO



