---
title: 'CACHI 77'
subtitle: 'JIC N° 04/05° SEDE - EPC N° 14 PROVINCIA DE SAN LUIS'
---

#
## Infraestructura

* NA 
    + mejora edilicia - Planificado 
    + Inicio de obra: Sin fecha de inicio 






## Mantenimiento

*  (2023) Albañileria / Pintura 
    + Reposición de paneles de Cielorraso, Reposición de percheros faltantes

*  (2023) Electricidad 
    + Gestión y Alquiler de GEM, Espacios seguros, Adecuacion de gas, Baja Tensión

*  (2023) Sanitarias 
    + Reemplazo de bombas,adecuacion tablero

*  (2022) Calefaccion y Refrigeracion 
    + Reemplazo Estufas Cachi 77 (Primaria)

*  (2022) Carpinterías 
    + Canilla Servicio Patio Huerta jardín, Concertina, Rejas y Generador, Reemplazo Vidrios en Escalera

*  (2022) Electricidad 
    + Adecuación Tablero Eléctrico, "Reposición ventiladores de techo

*  (2022) Sanitarias 
    + Adecuación Desengrasadora Primaria, Reponer tapa de tanque de agua, Reparación de cámaras cloacales, Reemplazo Inodoro

*  (2021) Carpinterías 
    + cambio de cerraduras

*  (2021) Electricidad 
    + Cambio de bombas de achiques

*  (2021) Incendio 
    + 2 EXTINTORES ABC X 5 KG





## Mobiliario

*  (2023) : Armario 2, Mesa inicial 10, Silla escolar 60 

*  (2022) : Mesa inicial 10, Pizarrón 4, Silla escolar 60 

*  (2021) : Armario 28, Escritorio 14, Mesa pupitre doble 90, Silla escolar 194 



