---
title: 'BERON DE ASTRADA 6351'
subtitle: 'PI EL RINCONCITO DE CLAUDIO - EEM N° 05/21° JUAN MANUEL FANGIO - EPC N° 16 DR. SOFANOR NOVILLO CORVALAN'
---

#


## Seguridad

*  Espacios seguros: 0 - Estado: Finalizado 
    + Guardia física: NO

*  Espacios seguros: 1 - Estado: Finalizado 
    + Guardia física: NO





## Mobiliario

*  (2022) : Escritorio 2, Mesa pupitre doble 18, Pizarrón 2, Silla escolar 38 

*  (2021) : Escritorio 2, Mesa pupitre doble 30, Pizarrón 2, Silla escolar 62 





## Mantenimiento

*  (2023) Calefaccion y Refrigeracion 
    + Reposicion de 2 calderas

*  (2023) Electricidad 
    + Seguridad para espacio digital 2do piso, Reposición de 10 ventialdores

*  (2023) Gas 
    + Instalación de gas por corte de suminist

*  (2022) Albañileria / Pintura 
    + Aulas secundaria del futuro

*  (2022) Calefaccion y Refrigeracion 
    + Colocación 12 placas dobles

*  (2022) Electricidad 
    + Recambio 6 ventiladores de pared, Reposición de 2 termotanques

*  (2022) Incendio 
    + Reposición de extintor en cocina

*  (2021) Albañileria / Pintura 
    + Secundaria del futuro en 2 aulas 1erPiso

*  (2021) Carpinterías 
    + 2 Rejas de protección de estufas

*  (2021) Electricidad 
    + coloc 6 purificadores de aire en aulas, Colocacion reflectores patio cubierto

*  (2021) Gas 
    + Reacondicionamiento de gas



