---
title: 'AYACUCHO 1680'
subtitle: 'JIN C (EPCJS 01/01°) - EPC N° 01 JUAN JOSE CASTELLI - CENS - UGEE N° 01'
---

#
## Infraestructura

* Fachadas (cambio de carpinterias y parasoles), nucleos sanitarios,(aula jines) mudanza de una sala, pintura completa, instalacion electrica y sanitario. Analizar instalacion termomecanica. red de proteccion en azotea. 
    + Mejora Edilicia - En Proyecto 
    + Inicio de obra: 3/2/2024 






## Mantenimiento

*  (2023) Calefaccion y Refrigeracion 
    + Cambio de aprox 10 equipos y calderas.

*  (2023) Electricidad 
    + Reparacion de Sistema de Vigilancia, Colocacion de ventiladores

*  (2023) Sanitarias 
    + Cambio de 2 inodoros

*  (2022) Gas 
    + Cambio de termotanque casa casera

*  (2022) Sanitarias 
    + Bajada de caño pluvial, Cambio de tapa en tanque de bombeo

*  (2021) Albañileria / Pintura 
    + Cambio de solados vinilicos

*  (2021) Sanitarias 
    + sanitarios de comedor niños y adultos





## Mobiliario

*  (2023) : Juego de patio 1, Piso antigolpe para juegos 1 

*  (2022) : Armario 4, Banco largo comedor 60 

*  (2021) : Armario 4, Escritorio 6, Mesa pupitre doble 60, Silla escolar 124 



