---
title: 'AVDA. SAN JUAN 2277'
subtitle: 'CENS N° 59 - EPC N° 25 GERVASIO POSADAS - EPA N° 25 GERVASIO POSADAS - JIN A (EPCJC 25/03°) [S] - ESEA EN DANZA MASTRAZZI CURSO VOCACIONAL DE DANZA Y EXPRESIÓN CORPORAL INFANTIL N° 05'
---

#
## Infraestructura

* Proyecto de accesibilidad y pintura general. agregar impermeabilización. expediente: construccion de galeria en patio para paso (jardin) 
    + mejora edilicia - Planificado 
    + Inicio de obra: 21/5/2025 






## Mantenimiento

*  (2023) Sanitarias 
    + Reparaciones en tanque de agua

*  (2022) Albañileria / Pintura 
    + Acondicionamiento de muro medianero

*  (2022) Electricidad 
    + Colocacion de 5 ventiladores

*  (2022) Gas 
    + Reemplazo General de Estufas pb, Adecuación de inst de gas a Normativa

*  (2022) Sanitarias 
    + Perdida en Cañeria Baños en comedor, Reponer inodoro en baño de niñas

*  (2021) Cubiertas / Impermeabilizaciones 
    + Reparación de filtraciónes, revoques

*  (2021) Gas 
    + Verificar instalacion de gas





## Mobiliario

*  (2022) : Armario 7, Banco largo comedor 20, Mesa inicial 10, Mesa usos múltiples 10, Silla escolar 60 

*  (2021) : Escritorio 2, Mesa pupitre doble 30, Mesa usos múltiples 1, Silla escolar 62 



