---
title: 'AVDA. LARRAZABAL 5001'
subtitle: 'EPC N° 10 ITALO AMERICO FORADORI - JIC N° 07/21°'
---

#


## Seguridad

*  Espacios seguros: 2 - Estado: En ejecución 
    + Guardia física: NO





## Mobiliario

*  (2023) : Mesa inicial 9, Silla escolar 54 

*  (2022) : Armario 8, Escritorio 2, Mesa inicial 2, Mesa integradora con escotadura 1, Mesa pupitre doble 16, Pizarrón 2, Silla escolar 46 

*  (2021) : Mesa pupitre doble 20, Silla escolar 40 





## Mantenimiento

*  (2023) Electricidad 
    + Protocolo Espacio seguro

*  (2022) Albañileria / Pintura 
    + Reaalización de dos aulas en PA, Rep. de Solado en patio del jardín

*  (2022) Calefaccion y Refrigeracion 
    + Prov. inst. placas termicas Planta Alta, Provision de protecciones de estufas

*  (2022) Incendio 
    + Reponer lanzas y tapas pvc en nichos, Reposición de mangueras en hidrantes

*  (2021) Albañileria / Pintura 
    + Reparación cantero y puerta lateral

*  (2021) Carpinterías 
    + Reparar estructura tela sombra-Patio JIC

*  (2021) Medios de elevación 
    + puesta en norma del ascensor



