---
title: 'AVDA. SAN JUAN 1545'
subtitle: 'PI LUCECITAS - CENS N° 18 - COLEGIO N° 01 BERNARDINO RIVADAVIA - ESC. DE COM. N° 36 ISAAC HALPERIN'
---

#
## Infraestructura

* Se realizará la reparación de revoques, filtraciones y trabajos de pintura. Instalación eléctrica completa. 
    + Mejora Edilicia - En Proyecto 
    + Inicio de obra: 07/03/2024 


* Impermeabilizacion de todas las terrazas y cubiertas. tratamiento de patologias estructurales, hierros expuestos. Tratamiento de humedad de cimientos. Optimizacion en instalaciones pluvial. 
    + Mejora Edilicia - Finalizado 
    + Finalizada el 4/12/2022 






## Mantenimiento

*  (2023) Albañileria / Pintura 
    + Secundaria del Futuro 2do Piso 3Etapa

*  (2023) Electricidad 
    + Reemplazo de ventiladores en aulas

*  (2022) Albañileria / Pintura 
    + Cálculo por Refuerzo Estructural, ACONDICIONAMIENTO DE AULAS, Secundaria del futuro Segundo Piso - Eta, Secundaria del Futuro 2do piso Etapa 2

*  (2022) Cubiertas / Impermeabilizaciones 
    + IMPERMEABILIZACIÓN DE AZOTEA

*  (2022) Electricidad 
    + Ventiladores en Secretaría 2do Piso

*  (2022) Sanitarias 
    + Adecuación de pluvial en patio aire y lu





## Mobiliario

*  (2023) : Escritorio 4, Mesa pupitre doble 60, Pizarrón 4, Silla escolar 124 

*  (2022) : Escritorio 4, Mesa pupitre doble 66, Pizarrón 22, Silla escolar 136 



