---
title: 'LOYOLA 1500'
subtitle: 'Sup Media Region VIII A Sup Media Tecnica Region VIII - ESC. TEC. N° 34 ING. ENRIQUE MARTIN HERMITTE'
---

#
## Infraestructura

* Itsf, acondicionamiento de taller en estudio de grabacion 
    + Obra Nueva - Licitación 
    + Inicio de obra: 26/12/2023 






## Mantenimiento

*  (2023) Albañileria / Pintura 
    + Instalacion eléctrica y pintura en aulas

*  (2023) Electricidad 
    + SECUNDARIAS DEL FUTURO- 3 AULAS, INSTALACION EN ESPACIOS SEGUROS

*  (2022) Albañileria / Pintura 
    + Pintura general de aula 23, CONEXIÓN CON MIRADOR COMASTRI, Pañol en taller audiovisual

*  (2022) Electricidad 
    + Canalizar alimentación eléctrica

*  (2022) Sanitarias 
    + Cambio 3 tanques de agua

*  (2021) Electricidad 
    + Alimentación electrica A°A° y telefonia, Adecuación instalación  eléctrica, Instalación eléctrica aula computacion

*  (2021) Gas 
    + Adecuacion instalacion de gas-Herreria





## Mobiliario

*  (2023) : Escritorio 3, Mesa pupitre doble 45, Pizarrón 3, Silla escolar 93 

*  (2022) : Escritorio 3, Mesa pupitre doble 45, Pizarrón 3, Silla escolar 93 

*  (2021) : Escritorio 4, Mesa pupitre doble 60, Mesa trabajo estante 4, Pizarrón 4, Silla escolar 124, Varios 8 



