---
title: 'FORMOSA 136'
subtitle: 'ESPACIO PRIMERA INFANCIA ESC. DE COM. N° 19 - ESC. DE COM. N° 19 JUAN MONTALVO - ESEA DANZA MASTRAZZI DANZA JUV. N°02'
---

#
## Infraestructura

* Polideportivo contempla la construcción de un volumen de apoyo y servicios, un área de cancha cubierta con estructura liviana de chapa y un área de cancha descubierta de verde que permite terreno absorbente en pulmón de manzana.
 
    + ampliacion - En Obra 
    + Inicio de obra: 20/01/2023 - Avance: 50% - Fecha de finalización: 22/1/2024 
    + Plan de obras 2021 - 2023 


* Accesibilidad, ascensor. (amparo) 
    + mejora edilicia - Finalizado 
    + Finalizada el 25/4/2022 
    + Plan de obras 2021 - 2023 






## Mantenimiento

*  (2023) Gas 
    + Reacondicionamiento del gas en el buffet, Reacondicionamiento de gas en buffet

*  (2021) Gas 
    + Readecuacion instalacion de gas}





## Mobiliario

*  (2023) : Escritorio 5, Mesa pupitre doble 75, Pizarrón 5, Silla escolar 155 

*  (2022) : Escritorio 6, Mesa pupitre doble 90, Pizarrón 6, Silla escolar 186 

*  (2021) : Escritorio 2, Mesa pupitre doble 30, Silla escolar 62 





## Seguridad

*  Espacios seguros: 1 - Estado: Suspendida ejecución 
    + Guardia física: NO



