---
title: 'PIO COLLIVADINO 436'
subtitle: 'ESC. TEC. N° 08 PAULA ALBARRACIN DE SARMIENTO'
---

#
## Infraestructura

* Adecuación de sanitarios e incorporación del sanitario para personas con movilidad reducida.
Restauración, conservación y tratamiento de prevención de las fachadas del edificio
Reparación / recomposición de los revoques en paramentos interiores afectados por humedad de cimientos, cielorrasos armados de yeso y solados.
Restauración de carpinterías y herrerías (puertas, ventanas, postigos, celosías y rejas de protección).
Pintura general de paramentos interiores y cielorrasos de todos los locales del establecimiento
Adecuación de instalación eléctrica a normativas vigentes, ejecución de instalación sanitaria nueva para los núcleos sanitarios, instalación pluvial.
Reinstalación de cañerías de gas exteriores en el interior del edificio. 
    + Mejora Edilicia - En Obra 
    + Inicio de obra: 01/08/2023 - Avance: 0% - Fecha de finalización: 31/7/2024 


* Reparacion de medianera 
    + Mejora Edilicia - Finalizado 
    + Finalizada el - 






## Mantenimiento

*  (2023) Electricidad 
    + Adecuación de 7 aulas S.F, INSTALACION EN ESPACIOS SEGUROS

*  (2022) Albañileria / Pintura 
    + Colocación protecciones bajo cornisas

*  (2022) Electricidad 
    + Espacio Digital

*  (2022) Incendio 
    + Proveer un extintor ABC de 5 kg

*  (2021) Calefaccion y Refrigeracion 
    + Cambio cuatro bombas de calefacción, Colocación de protecciones de estufas

*  (2021) Electricidad 
    + Reacondicionamiento eléctrico biblioteca, Instalación de purificadores





## Mobiliario

*  (2023) : Escritorio 7, Mesa pupitre doble 105, Silla escolar 217 

*  (2022) : Armario 9, Escritorio 2, Mesa pupitre doble 30, Silla escolar 62 

*  (2021) : Escritorio 2, Mesa pupitre doble 30, Mesa trabajo estante 6, Silla escolar 62, Varios 12 





## Seguridad

*  Espacios seguros: 1 - Estado: En ejecución 
    + Guardia física: NO



