---
title: 'BOLIVAR 1235 - PERU 1236'
subtitle: 'ENS N° 03 BERNARDINO RIVADAVIA (SEDE) - ENS N° 03 BERNARDINO RIVADAVIA (Anexo Nivel Inicial)'
---

#


## Mobiliario

*  (2023) : Armario 4, Escritorio 10, Mesa pupitre doble 70, Pizarrón 16, Silla escolar 170 

*  (2022) : Escritorio 4, Mesa pupitre doble 67, Piso antigolpe para juegos 100, Pizarrón 4, Silla escolar 8 

*  (2021) : Escritorio 8, Mesa pupitre doble 120, Pizarrón 6, Silla escolar 124 





## Mantenimiento

*  (2023) Electricidad 
    + Adecuación de SDF 2023

*  (2023) Otros Servicios 
    + Prov y colocacion de ventanas en aulas

*  (2022) Cubiertas / Impermeabilizaciones 
    + Cambio de cubierta de chapa y cielorraso

*  (2022) Gas 
    + Adecuacion de instal de gas a normativa

*  (2022) Medios de elevación 
    + Reparacion de ascensor y reemplazo tapas

*  (2022) Sanitarias 
    + Cambio de bajadas pluviales en fachada

*  (2021) Albañileria / Pintura 
    + Demolicion tabique aula y adec IFCI, Adecuacion de 4 aulas para SDF

*  (2021) Carpinterías 
    + Provision y colocacion de ventana en com, Puerta de seguridad en calle Bolivar

*  (2021) Medios de elevación 
    + Adecuacion y puesta norm ascensor

*  (2021) Otros Servicios 
    + Colocacion de purificadores



