---
title: 'AVDA. PTE. MANUEL QUINTANA 31'
subtitle: 'SUPERVISIÓN DE 1 - JIC N° 04/01° CINCO ESQUINAS - EPC N° 02 DOMINGO FAUSTINO SARMIENTO - ESC. DE MUSICA N° 16 - ESEA EN DANZA MASTRAZZI CURSO VOCACIONAL DE DANZA Y EXPRESIÓN CORPORAL INFANTIL N° 04 - ESEA EN DANZA RAMICONE CURSO VOCACIONAL DE FOLKLORE N° 04'
---

#
## Infraestructura

* Acondicionamiento de fachadas/ adecuacion de supervision de1 
    + Mejora Edilicia - En Obra 
    + Inicio de obra: 1/12/2022 - Avance: 28% - Fecha de finalización: 30/12/2023 






## Mantenimiento

*  (2023) Electricidad 
    + Instalacion  Espacios Seguros, Reemplazar 2 ventiladores en jardín

*  (2022) Albañileria / Pintura 
    + Recambio de tramo de conducto pluvial

*  (2022) Electricidad 
    + Remplazo de ventiladores

*  (2022) Gas 
    + Instalaciones de gas

*  (2022) Sanitarias 
    + Reposición de Bidet vandalizado

*  (2021) Albañileria / Pintura 
    + Recambio de solados en patio Jardín, Apertura de la puerta de Quintana, Apuntalamiento

*  (2021) Electricidad 
    + Reemplazo de Ventiladores de Pared

*  (2021) Sanitarias 
    + Limpieza y desinfección tanque cisterna, Recambio de tapa de inspección





## Mobiliario

*  (2022) : Armario 2, Mesa inicial 5, Pizarrón 7, Silla escolar 30, Varios 1 

*  (2021) : Banco largo comedor 36, Escritorio 4, Juego de patio 1, Mesa usos múltiples 18, Piso antigolpe para juegos 60, Silla escolar 124, Varios 10 



