---
title: 'GUEMES 3859'
subtitle: 'ENS N° 06 VICENTE LOPEZ Y PLANES'
---

#
## Infraestructura

* Plan mejora edif historica adecuacion  inst electrica , gas-calefaccion patio , cubierta , reparacion revoques y pintura en areas significativas 
    + mejora edilicia - Planificado 
    + Inicio de obra: Sin fecha de inicio 






## Mantenimiento

*  (2022) Electricidad 
    + Cables y pintura sala computacion

*  (2022) Gas 
    + Cambio de llaves de paso de estufas

*  (2022) Otros Servicios 
    + Secundaria del Futuro etapa 5

*  (2021) Cubiertas / Impermeabilizaciones 
    + Cambio de membrana impermeable terrazas, Pintura sobre membrana geotextil

*  (2021) Electricidad 
    + Circuito independiente para luces emerg, Provisión y colocacion de 4 ventiladores

*  (2021) Incendio 
    + Instalacion electrica taller VLyPlanes

*  (2021) Medios de elevación 
    + Habilitacion del ascensor





## Mobiliario

*  (2023) : Armario 2 

*  (2022) : Armario 6, Escritorio 4, Mesa pupitre doble 60, Pizarrón 4, Silla escolar 124 

*  (2021) : Armario 3, Escritorio 4, Mesa pupitre doble 60, Pizarrón 5, Silla escolar 124 





## Seguridad

*  Espacios seguros: 2 - Estado: Finalizado 
    + Guardia física: NO



