---
title: 'CARLOS PELLEGRINI 1515'
subtitle: 'INST. DE ENSEÑANZA SUPERIOR EN LENGUAS VIVAS JUAN RAMÓN FERNÁNDEZ'
---

#
## Infraestructura

* Puesta en valor del sum y accesibilidad basica 
    + Mejora Edilicia - En Obra 
    + Inicio de obra: 1/3/2023 - Avance: 26% - Fecha de finalización: 30/12/23 


* Puesta en valor de la escalera 
    + Mejora Edilicia - Finalizado 
    + Finalizada el 19/11/2021 






## Mantenimiento

*  (2022) Albañileria / Pintura 
    + Acondicionamiento de piso aula fonética

*  (2022) Cubiertas / Impermeabilizaciones 
    + Refuerzo Especial de Control de Plagas -

*  (2022) Incendio 
    + Reposición de Accesorios de IFCI Vandali, Prov de Extintores acorde a planos evacu

*  (2021) Albañileria / Pintura 
    + SDF 4TO AÑO, Refuncionalizacion para comedor, Secundarias del futuro 4to año





## Mobiliario

*  (2022) : Escritorio 4, Mesa pupitre doble 60, Pizarrón 4, Silla escolar 124 

*  (2021) : Escritorio 4, Mesa pupitre doble 60, Pizarrón 4, Silla escolar 124 





## Seguridad

*  Espacios seguros: 1 - Estado: A confirmar 
    + Guardia física: SI



