---
title: 'MONTIEL 3826'
subtitle: 'JII N° 01/20° - EPC N° 22 RUFINO LURO CAMBACERES'
---

#
## Infraestructura

* NA 
    + mejora edilicia - Planificado 
    + Inicio de obra: Sin fecha de inicio 






## Mantenimiento

*  (2023) Carpinterías 
    + Obra de seguridad por vandalismo

*  (2023) Electricidad 
    + Proveer  luminarias exteriores, Sistema de alarma y vigilancia

*  (2023) Sanitarias 
    + Ejecucion camaras cloacales 2 etapa

*  (2022) Carpinterías 
    + Proveer y colocar puerta reja, Prov. coloc de 3 cerraduras por vandalis, Prov. coloc. 4 vidrios por vandalismo

*  (2022) Gas 
    + Adecuar instalación de gas

*  (2022) Sanitarias 
    + Ejecución de cámaras cloacales.

*  (2021) Albañileria / Pintura 
    + Tabique para canteroy reja de protección

*  (2021) Sanitarias 
    + 2 bombas centrifugas,achique,tanque, Provision de camion atmosferico





## Mobiliario

*  (2023) : Banco largo comedor 20, Juego de patio 1, Mesa inicial 15, Mesa integradora con escotadura 1, Piso antigolpe para juegos 60, Silla escolar 90, NA 2 





## Seguridad

*  Espacios seguros: 2 - Estado: Colocada a configurar 
    + Guardia física: NO



