---
title: 'ROGELIO YRURTIA 5806'
subtitle: 'EPC N° 19 NACIONES UNIDAS - JIC N° 01/15° - CAIYJ CLUB SAAVEDRA'
---

#
## Infraestructura

* Completo o por etapas de obra / acondicionamiento de aulas, sanitarios y pintura general 
    + Mejora Edilicia - Planificado 
    + Inicio de obra:08/01/2024 



## Mobiliario

*  (2022) : Armario 2, Escritorio 2, Mesa pupitre doble 52, Silla escolar 104 





## Mantenimiento

*  (2022) Albañileria / Pintura 
    + Reemplazo de solado en aula PB, Recambio de solados biblioteca

*  (2022) Carpinterías 
    + Remplazo de red de proteccion en patio

*  (2021) Albañileria / Pintura 
    + Reparación de timpano, Cambio de solado vicedirección,secretar, Construcción de contrapiso

*  (2021) Calefaccion y Refrigeracion 
    + Adecuación de sistema de calefaccíon

*  (2021) Carpinterías 
    + Coloc red protección 3 aberturas, Colocacion de Pizarrones

*  (2021) Cubiertas / Impermeabilizaciones 
    + Reposición de tejas coloniales en cubie

*  (2021) Electricidad 
    + Prov, coloc portero electrico jardin






