---
title: 'AVDA. CORRIENTES 4261'
subtitle: 'ESPACIO PRIMERA INFANCIA ESC. DE COM. N° 25 - ENS N° 07 JOSE MARIA TORRES - ESC. DE COM. N° 08 PATRICIAS ARGENTINAS - ESC. DE COM. N° 25 SANTIAGO DE LINIERS'
---

#


## Mobiliario

*  (2023) : Escritorio 4, Mesa pupitre doble 60, Pizarrón 4, Silla escolar 124 

*  (2022) : Armario 8, Escritorio 4, Mesa pupitre doble 60, Pizarrón 4, Silla escolar 124, Varios 3 

*  (2021) : Armario 4, Banco largo comedor 20, Escritorio 5, Mesa pupitre doble 75, Mesa usos múltiples 10, Pizarrón 7, Silla escolar 155 





## Mantenimiento

*  (2023) Albañileria / Pintura 
    + Secundaria del Futuro en 2 piso

*  (2023) Carpinterías 
    + Cambio de 4 cerraduras puerta antipánico

*  (2023) Electricidad 
    + Reemplazo de 6 ventiladores de techo

*  (2023) Medios de elevación 
    + Ascensor dañado por vandalismo, Cambio de puerta cabina del ascensor

*  (2023) Sanitarias 
    + Reposición de 3 inodoros

*  (2022) Albañileria / Pintura 
    + 4 aulas - Secundaria del Futuro

*  (2022) Carpinterías 
    + Prov. Coloc. rejas de seguridad en aula

*  (2022) Electricidad 
    + Reponer lámparas o artefactos

*  (2022) Incendio 
    + Reposicion de 1 matafuego ABC de 5 k, Reemplazo de 1 matafuegos ABC 5kg

*  (2022) Medios de elevación 
    + Reparación de ascensor n°2

*  (2021) Albañileria / Pintura 
    + Reparar e impermeab. medianera oeste, Aulas del Futuro- 5 aulas 2do piso

*  (2021) Electricidad 
    + Reponer ventiladores en diversas aulas, Instalacion 3 purificadores de aire

*  (2021) Sanitarias 
    + Prov. coloc  bomba de caudal de entrada



