---
title: 'AVDA. ENTRE RIOS 1341 - AVDA. ENTRE RIOS 1349 - AVDA. ENTRE RIOS 1359 - CONSTITUCION 1839'
subtitle: 'CENS N° 44 - JIN A (EPCJC 21/03°) - EPC N° 21 CARLOS PELLEGRINI - Bib.del Docente Dist.3 Carlos Pellegrini - EPA N° 22 CARLOS PELLEGRINI - JIN A (EPCJS 22/03°) - EPC N° 22 CARLOS PELLEGRINI - Sup Primaria DE03 A - Centro de Terminalidad a Distancia[sede] - Sup Adultos Region I A'
---

#
## Infraestructura

* Adecuacion  calefaccion, inst electrica , patio , muros ,cubierta, acesibilidad basica  , pintura en areas significativas, adecuacion cocina. 
    + mejora edilicia - Planificado 
    + Inicio de obra: Sin fecha de inicio 






## Mantenimiento

*  (2023) Electricidad 
    + Instalación en espacios seguros

*  (2023) Gas 
    + Adecuación de inst de gas a Normativa, REPONER MEDIDOR DE GAS EN COCINA, Reparacion segun informe MetroGas

*  (2022) Albañileria / Pintura 
    + Reparar revoques de aula de plástica, Pintura de pasillo y 2 hall

*  (2022) Carpinterías 
    + Sustitucion Puertas baño Jardin

*  (2022) Cubiertas / Impermeabilizaciones 
    + Reparar filtraciones en cubierta, Elemento estructural para filtraciones

*  (2022) Electricidad 
    + Reemplazar y suministrar ventiladores, Colocar Cinco Ventiladores distribuidos

*  (2022) Gas 
    + Adecuación de inst de gas a Normativa

*  (2022) Otros Servicios 
    + RETIRO DE ARBOL, Retiro de Materiales o Restos de Obra

*  (2022) Sanitarias 
    + Sustitucion de inodoro b.discapacitados

*  (2021) Albañileria / Pintura 
    + Rep,pintar cielorraso biblioteca,pasillo

*  (2021) Gas 
    + Verificar instalacion de gas





## Mobiliario

*  (2023) : Mesa pupitre doble 30, Pizarrón 9, Silla escolar 90 

*  (2022) : Armario 2, Mesa pupitre doble 30, Silla escolar 70 

*  (2021) : Banco largo comedor 10, Mesa usos múltiples 5 





## Seguridad

*  Espacios seguros: 2 - Estado: Suspendida ejecución 
    + Guardia física: NO



