---
title: 'AVDA. CORDOBA 1951 - PARAGUAY 1950'
subtitle: 'ENS N° 01 LENGUAS VIVAS PRES. R. S. PEÑA - LICEO N° 04 R. DE ESCALADA DE SAN MARTIN - ESEA  DANZA RAMICONE  FOLKLORE N° 21 - ESC. DE COM. N° 10 ISLAS MALVINAS'
---

#
## Infraestructura

* Impermeabilizacion 
    + Mejora Edilicia - En Obra 
    + Inicio de obra: 22/7/2023 - Avance: 78% - Plazo: 240 días 


* 2do año 
    + SDF - En Obra 
    + Inicio de obra: 06/02/2023 - Avance: 60% - Plazo: 60 días 






## Mantenimiento

*  (2023) Carpinterías 
    + Prov,coloc 3 puertas reja acceso aulas

*  (2023) Sanitarias 
    + Cambio de 3 inodoros

*  (2022) Albañileria / Pintura 
    + Secundaria del futuro, Reparacion de cielorrasos sobre caja esc, Cambio de tanques de reserva, Presupuesto aulas SDF

*  (2022) Calefaccion y Refrigeracion 
    + Cambio de 3 estufas

*  (2022) Carpinterías 
    + Provisión e instalación de rejas en dife

*  (2022) Electricidad 
    + Cambio de cableado telefonico, Retiro artef iluminacion y colocac LED

*  (2022) Incendio 
    + Cambio de lanzas, Rep. y coloc señaleticas

*  (2022) Medios de elevación 
    + Reparacion variador de control  maniobra

*  (2022) Otros Servicios 
    + Volquete para retiro de materiales

*  (2022) Sanitarias 
    + Cambio de bomba de achique

*  (2021) Albañileria / Pintura 
    + demolicion y reconstruccion de cielorras

*  (2021) Gas 
    + Puesta a normativa instalacion de gas, Cambio de 7 estufas en aulas, Cambio de termotanque normativa Metrogas

*  (2021) Incendio 
    + Reemplazo de 3 extintores ABC x 5 kg

*  (2021) Sanitarias 
    + Impermeabilizacion de canaletas





## Mobiliario

*  (2023) : Escritorio 6, Juego de patio 1, Mesa pupitre doble 90, Piso antigolpe para juegos 1, Pizarrón 6, Silla escolar 186 

*  (2022) : Armario 1, Banco largo comedor 2, Escritorio 6, Mesa pupitre doble 90, Pizarrón 6, Silla escolar 186 

*  (2021) : Escritorio 5, Mesa pupitre doble 75, Pizarrón 5, Silla escolar 155 



