---
title: 'ALEJANDRO MAGARIÑOS CERVANTES 5068'
subtitle: 'ESEA DANZA N° 02 JORGE DONN - ESEA ARTE CERAMICO Nª 2 FERNANDO ARRANZ'
---

#
## Infraestructura

* 2do año 
    + SDF - Finalizado 
    + Finalizada el 1/4/2023 


* Instalacion electrica completa, sanitarios 
    + Mejora Edilicia - Finalizado 
    + Finalizada el 22/9/2022 


* Construccion de sala de tableros para edesur 
    + Mejora Edilicia - Fracasado 
    + Inicio de obra: Sin fecha de inicio 


* Construccion de sala de tableros para edesur 
    + Mejora Edilicia - Licitación 
    + Inicio de obra: 15/11/2023 






## Mantenimiento

*  (2022) Electricidad 
    + Adecuacion biblioteca

*  (2022) Sanitarias 
    + Destapación de piletas decantacion, Destapación de piletas de decantación

*  (2021) Albañileria / Pintura 
    + TERMINACIONES SALONES DE DANZAS Y HERRER

*  (2021) Carpinterías 
    + Baranda protectora, Cerramiento de seguridad en anexo Muratu

*  (2021) Electricidad 
    + Instalacion de 16 equipos purificadores

*  (2021) Gas 
    + Adecuaciones gas, extracción y ventilaci

*  (2021) Sanitarias 
    + Destapacion de piletas de decantacion





## Mobiliario

*  (2023) : Escritorio 7, Locker 20, Mesa pupitre doble 105, Pizarrón 7, Silla escolar 217 

*  (2022) : Escritorio 7, Mesa pupitre doble 105, Pizarrón 7, Silla escolar 93 

*  (2021) : Escritorio 4, Mesa pupitre doble 50, Silla escolar 104 



