---
title: 'AVDA. JUJUY 255'
subtitle: 'ESC. TEC. N° 26 CONFEDERACION SUIZA'
---

#
## Infraestructura

* Sanitarios. (fondos inet) 
    + mejora edilicia - Finalizado 
    + Finalizada el - 


* NA 
    + mejora edilicia - Planificado 
    + Inicio de obra: Sin fecha de inicio 






## Mantenimiento

*  (2023) Albañileria / Pintura 
    + Realizar 3 aulas del futuro

*  (2023) Calefaccion y Refrigeracion 
    + Reemplazo de 2 estufas

*  (2023) Carpinterías 
    + Prov. e instalacion cortina blackout aul

*  (2023) Electricidad 
    + 2DA ETAPA-Adecuacion de inst de gas, Ejecución Espacios Seguros

*  (2023) Gas 
    + Adecuacion de gas en el edificio, Carpinterás - Placas antihumeddad

*  (2022) Calefaccion y Refrigeracion 
    + Provisión y colocac. equipos frio/calor

*  (2021) Albañileria / Pintura 
    + Retiro de vegetales en medianera, Adecuación Aulas del Futuro 5º año

*  (2021) Carpinterías 
    + Cortinas Blackout

*  (2021) Cubiertas / Impermeabilizaciones 
    + Colocación de Placas antihumedad

*  (2021) Electricidad 
    + reemplazo central telefónica, Rep central de cámaras de seguridad, Intalación de purificadores de Aire

*  (2021) Gas 
    + Pruebas de hermeticidad y adecuación

*  (2021) Incendio 
    + Reponer 2 extintores





## Mobiliario

*  (2023) : Escritorio 3, Mesa pupitre doble 45, Pizarrón 3, Silla escolar 93 

*  (2022) : Escritorio 3, Mesa pupitre doble 45, Pizarrón 3, Silla escolar 93 

*  (2021) : Escritorio 3, Mesa pupitre doble 45, Pizarrón 3, Silla escolar 93 





## Seguridad

*  Espacios seguros: 2 - Estado: Finalizado 
    + Guardia física: SI



