---
title: 'AVELINO DIAZ 2356'
subtitle: 'EPC N° 22 HIPOLITO BOUCHARD'
---

#
## Infraestructura

* Evaluacion estructural de varias fisura (muros de aula, cocina y escaler). expte?
Plan mejora de patio+muros+acond gas-electricidad+ sanitarios y pintura en areas significativaspatios amerita mejora en pisos y pintura. humedad ascendente en medianera de aulas y comedor. acondicionamiento de cielorrasos dela circulación del primer piso. acondicionamiento de instalacion electrica y termomecanica. acondicionamiento del sanitarios del piso 1. la accesibilidad si bien es básica amerita resolución de algunos desniveles internos en sus recorridos.  

 
    + mejora edilicia - En Proyecto 
    + Inicio de obra: 15/4/2024 






## Mantenimiento

*  (2022) Albañileria / Pintura 
    + Adecuación de Escalera contrafrente

*  (2022) Calefaccion y Refrigeracion 
    + Instalación de A°A° de tipo split

*  (2022) Electricidad 
    + Instalación de purificadores

*  (2021) Cubiertas / Impermeabilizaciones 
    + Cambio de chapas del techo del patio





## Mobiliario

*  (2022) : Escritorio 1, Mesa pupitre doble 12, Silla escolar 25 



