---
title: 'CONESA 1855'
subtitle: 'LICEO N° 09 SANTIAGO DERQUI'
---

#
## Infraestructura

* NA 
    + mejora edilicia - Planificado 
    + Inicio de obra: Sin fecha de inicio 






## Mantenimiento

*  (2023) Albañileria / Pintura 
    + Cambio de solado de patio

*  (2023) Calefaccion y Refrigeracion 
    + Prov y coloc estructura apoyo de 4 unid.

*  (2023) Carpinterías 
    + Pintura de fachada y provision y colocac

*  (2023) Electricidad 
    + Instalacion equipos aire acondicionado

*  (2023) Sanitarias 
    + Reemplazo de tanque de reserva

*  (2022) Albañileria / Pintura 
    + Adecuación preceptoria PA, Colocacion piso sala de lectura, Adecuacion laboratorio

*  (2022) Carpinterías 
    + Adecuacion sala de computacion

*  (2022) Electricidad 
    + Aulas secundaria del futuro, Instalacion electrica sala de musica, Instalacion electrica sala de profesores

*  (2021) Albañileria / Pintura 
    + Aulas del futuro, Integracion sala de arte y tecnologia

*  (2021) Calefaccion y Refrigeracion 
    + COLOCACION DE AIRE ACONDICIONADO ENAULAS





## Mobiliario

*  (2022) : Escritorio 3, Mesa pupitre doble 45, Pizarrón 3, Silla escolar 93 

*  (2021) : Escritorio 3, Mesa pupitre doble 45, Pizarrón 3, Silla escolar 106 



