---
title: 'MARTINEZ CASTRO 3061'
subtitle: 'POLIDEPORTIVO - EEM N° 02/19° - PI JAURETCHITOS - EEM N° 02/19° ARTURO JAURETCHE - CAEBYT N° 16 - CAEBYT N° 06 - EPC N° 20 MAESTRO CARLOS A. CARRANZA - CAIYJ CLUB DE JOVENES ARTURO JAURETCHE - JII N° 10/19° ([A]) - PI NOCHECITAS'
---

#
## Infraestructura

* 3er año 
    + SDF - Finalizado 
    + Finalizada el - 






## Mantenimiento

*  (2023) Carpinterías 
    + Automatización de portones

*  (2023) Electricidad 
    + INSTALACION EN ESPACIOS SEGUROS, Secundarias del Futuro

*  (2023) Incendio 
    + Instalación contra incendio., Instalación contra incendio.

*  (2022) Carpinterías 
    + Reparación de mástil en Gral

*  (2022) Electricidad 
    + 12 reflectores para SUM e Ingreso

*  (2022) Medios de elevación 
    + Proveer e instalar tablero en ascensor

*  (2022) Sanitarias 
    + Reparacion de pluvial patio trasero

*  (2021) Calefaccion y Refrigeracion 
    + Instalacion de 2 purificadores de aire

*  (2021) Carpinterías 
    + Reparar paño de reja predio

*  (2021) Cubiertas / Impermeabilizaciones 
    + Impermeabiliz cubierta,pintura techo

*  (2021) Electricidad 
    + Proveer, instalar para rayos por vandal, Prov, inst de tablero en ascensor

*  (2021) Gas 
    + Puesta en norma de inst de gas, adecuación de mecheros a normativa., Prov, instalar termotanque casa casero

*  (2021) Incendio 
    + Rep. y prov. nicho, lanzas y manguera

*  (2021) Medios de elevación 
    + Adecuación de ascensor





## Mobiliario

*  (2023) : Escritorio 2, Mesa pupitre doble 30, Pizarrón 2, Silla escolar 62 

*  (2022) : Escritorio 3, Mesa pupitre doble 45, Pizarrón 3, Silla escolar 93 

*  (2021) : Escritorio 3, Mesa pupitre doble 45, Pizarrón 3, Silla escolar 93 



