---
title: 'AVDA. LARRAZABAL 4520'
subtitle: 'EPC N° 05 ARMADA ARGENTINA - EPA N° 05 ARMADA ARGENTINA - CECIE N° 21 - JII N° 06/21°'
---

#
## Infraestructura

* Instalación eléctrica completa, filtraciones, cambio de parasoles, pintura general 
    + mejora edilicia - En Obra 
    + Inicio de obra: 22/10/2023 - Avance: 0% - Fecha de finalización: 16/10/2024 


* Terreno propio sobrante escuela larrazabal ex beron de astrada 6351 
    + remplazo - Planificado 
    + Inicio de obra: Sin fecha de inicio 






## Mantenimiento

*  (2023) Sanitarias 
    + Depósito para peluquería

*  (2022) Albañileria / Pintura 
    + Realizar 3 cateos en zonas indicadas

*  (2022) Carpinterías 
    + Cambio de 7 picaportes en la escuela por, Reposición de ventilador y teléfono por, Cambio de vidrios por vandalismo.

*  (2022) Electricidad 
    + Reposición de ventiladores de pared

*  (2022) Incendio 
    + Cambio de matafuegos

*  (2022) Sanitarias 
    + Cambio de bombas de calefacción, Cambio de inodoro roto x vandalismo

*  (2021) Carpinterías 
    + Cambio de cerradura porton de entrada, Cambio de vidrio por vandalismo, Cambio de cerradura x vandalismo, Cambio de cerradura vandalizada, Cambio de cerradura en dirección x vanda

*  (2021) Electricidad 
    + Luminarias en hall y salon comedor, Extensión con caño daisa y dos tomas

*  (2021) Sanitarias 
    + Cambio de cañerias de bombeo caldera, Realizar cámara de inspección





## Mobiliario

*  (2023) : Mesa integradora con escotadura 1 

*  (2021) : Armario 10 





## Seguridad

*  Espacios seguros: 1 - Estado: Finalizado 
    + Guardia física: NO

*  Espacios seguros: 1 - Estado: Finalizado 
    + Guardia física: NO



