---
title: 'AVDA. PUEYRREDON 630'
subtitle: 'Supervisión de Nivel Primaria DE 02 - EPC N° 14 JUAN MARTIN DE PUEYRREDON - EPA N° 14 JUAN MARTIN DE PUEYRREDON'
---

#
## Infraestructura

* Adecuacion de pileta y sus instalaciones plan mejora de patio+muros+acond gas-electricidad+ sanitarios y pintura en areas significativas 
    + mejora edilicia - Planificado 
    + Inicio de obra: Sin fecha de inicio 






## Mantenimiento

*  (2023) Electricidad 
    + Espacios seguros Inst. alarmas y sensore

*  (2023) Sanitarias 
    + Reposición termo tanque en casa casero

*  (2022) Albañileria / Pintura 
    + Refuerzo estructural losa y vigas

*  (2022) Calefaccion y Refrigeracion 
    + Recambio de estufas

*  (2021) Cubiertas / Impermeabilizaciones 
    + Readecuacion de inst pluvial en terraza

*  (2021) Electricidad 
    + Reemplazo de tablero principal





## Mobiliario

*  (2023) : Escritorio 6, Mesa pupitre doble 90, Silla escolar 180 

*  (2022) : Armario 14, Banco largo comedor 64, Escritorio 7, Mesa pupitre doble 26, Mesa usos múltiples 32, Pizarrón 8, Silla escolar 61 

*  (2021) : Escritorio 2, Mesa pupitre doble 30, Pizarrón 6, Silla escolar 62 





## Seguridad

*  Espacios seguros: 1 - Estado: Finalizado 
    + Guardia física: NO



