---
title: 'AVDA. CRAMER 2136'
subtitle: 'EEM N° 05/10° HEROES DE MALVINAS'
---

#
## Infraestructura

* 2do año 
    + sdf - Finalizado 
    + Finalizada el - 






## Mantenimiento

*  (2023) Albañileria / Pintura 
    + Puesta en valor patio ppal, Puesta en valor solado de escenario SUM

*  (2023) Carpinterías 
    + Reparacion de pergola, Herreria patio ppal, Prov.Coloc protección en escalera

*  (2023) Electricidad 
    + 2 aulas secundaria del futuro, Pintura de fachada mas Provisión e insta

*  (2022) Albañileria / Pintura 
    + Cambio de solado de 4 aulas PB, SUM

*  (2022) Carpinterías 
    + Cambio de ventanas pasillo PA

*  (2022) Electricidad 
    + Aulas secundaria del futuro, Prov. coloc. 28 luces de emergencia

*  (2022) Gas 
    + PROVISION Y COLOCACION MECHEROS

*  (2021) Electricidad 
    + Provision y colocacion de central telefo





## Mobiliario

*  (2023) : Escritorio 2, Mesa pupitre doble 30, Pizarrón 2, Silla escolar 62, NA 1 

*  (2022) : Escritorio 2, Mesa pupitre doble 30, Pizarrón 2, Silla escolar 62 



