---
title: 'AVDA. DEL LIBERTADOR 4903'
subtitle: 'EPC N° 30 GRANADEROS DE SAN MARTIN - JIC N° 02/09° GRANADEROS DE SAN MARTIN - ESCUELA DE MAESTROS ([A] 07)'
---

#
## Infraestructura

* Adecuacion de fachada+  patios + muros+carpinterias+   inst electrica + inst gas-calefacc y pintura en areas significativas evaluar posible mejora en pileta -instalaciones-. Catalogación. 
    + Mejora Edilicia - Planificado 
    + Inicio de obra: 01/08/2024 






## Mantenimiento

*  (2023) Electricidad 
    + instalación de seguridad, Readecuación de instalación electrica

*  (2023) Sanitarias 
    + Cambio de inodoro por rotura

*  (2022) Albañileria / Pintura 
    + pintura de friso y entrepiso del gimnasi, Pintura de cielorrasos/techos

*  (2022) Calefaccion y Refrigeracion 
    + Cambio de equipo de calefacción

*  (2022) Electricidad 
    + Instalación eléctrica sector hidroponia., Instalar 17 tomas para TV en aulas

*  (2021) Carpinterías 
    + Protección de hierro de todas las estufa

*  (2021) Electricidad 
    + Instalacion de 2 ventiladores

*  (2021) Medios de elevación 
    + Puesta en normativa ascensor

*  (2021) Sanitarias 
    + Cambio termotanque vivienda casera





## Mobiliario

*  (2023) : Escritorio 7, Mesa pupitre doble 65, Pizarrón 1, Silla escolar 137 



