---
title: 'TERRADA 3983'
subtitle: 'EPC N° 04 CNEL. MAYOR I. ALVAREZ THOMAS - JIN B (EPCJC 04/16°) JUANA AZURDUY'
---

#
## Infraestructura

* NA 
    + Mejora Edilicia - Finalizado 
    + Finalizada el - 






## Mantenimiento

*  (2023) Albañileria / Pintura 
    + Reacondicionando los baños

*  (2023) Calefaccion y Refrigeracion 
    + RETRO, PROV Y COLOCACION DE PERSIANAS

*  (2023) Electricidad 
    + Espacio de seguridad

*  (2022) Carpinterías 
    + Desratizacion y persianas

*  (2022) Electricidad 
    + Luces de emergencia natatorio, Arreglo ascensor por ingreso de agua Se, Colocacion tomacorrientes en aulas

*  (2021) Calefaccion y Refrigeracion 
    + Reparacion bombas caldera

*  (2021) Carpinterías 
    + Colocacion de vidrios, Cambio de persianas

*  (2021) Cubiertas / Impermeabilizaciones 
    + Arreglo filtraciones sala calderas

*  (2021) Incendio 
    + Adecuación IFCI Falta adjuntar presupues

*  (2021) Medios de elevación 
    + Arreglo Ascensor, Arreglo ascensor por sobrecarga, balanza

*  (2021) Saneamiento 
    + Cambiar los tanques de reserva





## Mobiliario

*  (2021) : Banco largo comedor 90, Mesa usos múltiples 45 



