---
title: 'LACARRA 535'
subtitle: 'Sup Media Tecnica Region V Oeste - ESC. TEC.  N° 17 BRIG. GRAL. CORNELIO SAAVEDRA - CAIYJ LACARRA'
---

#
## Infraestructura

* Área administrativa: sanitario del sector a nuevo. Se colocara cielorrasos suspendidos en todo el área. Se realizará una nueva inst. Eléctrica. Se pintara completamente todo el sector.
En el edificio donde funciona el taller de electrónica, en planta baja: 
Puesta en valor de los sanitarios de docentes, office, sanitarios de alumnos y taller de electrónica.
En la planta alta de este mismo edificio, puesta en valor del aula de computación y el pasillo a fin de dar respuesta a la salida de emergencia. 
En el taller de hormigón armado que se encuentra en otro sector de la escuela sobre planta baja, se dará intervención al sanitario existente de docentes y al patio descubierto.
Puesta en valor del sum y biblioteca.
Intervencion de cubiertas (membranas, asbesto, cambio de tejas y chapas,etc..)
Cambio de tanques e instalación eléctrica. 
    + Mejora Edilicia - Licitación 
    + Inicio de obra: 20/10/2023 






## Mantenimiento

*  (2023) Albañileria / Pintura 
    + Desmontaje cielorraso sector administrac

*  (2023) Electricidad 
    + Adecuación de 5 aulas Sec. Futuro, INSTALACION EN ESPACIOS SEGUROS, Cableado de sistema de emergencia

*  (2022) Incendio 
    + IFCI Apto para su uso

*  (2022) Medios de elevación 
    + Reparación ascensor edificio trasero, Reparación ascensor patio





## Mobiliario

*  (2023) : Escritorio 5, Mesa pupitre doble 75, Pizarrón 5, Silla escolar 155 

*  (2022) : Mesa pupitre doble 105, Pizarrón 7, Silla escolar 247 



