---
title: 'JUAN CARLOS GOMEZ 253'
subtitle: 'PI ESPACIO HUELLITAS - ESC. DE COM. N° 18 REINO DE SUECIA - EEM N° 01/05° E.REINGRESO N. J.MORRESI - PI ESPACIO NOCHERITOS'
---

#
## Infraestructura

* Acondicionamiento inst electrica incendio, carpinteria arreglo de revoque y piso patio + adecuacion casa casero para re ubicación aula adecuacion pintura interior pasillos (dgmesc pintaria aulas ) y areas significantes  + patio y fachada 
    + Mejora Edilicia - En Obra 
    + Inicio de obra: 1/12/2022 - Avance: 33% - Plazo: 180 






## Mantenimiento

*  (2022) Albañileria / Pintura 
    + Aulas del Futuro aulas de 1er año Revisa

*  (2022) Electricidad 
    + Adecuar inst eléctrica- Oficinas

*  (2022) Sanitarias 
    + Realizar guardaganado en salida, Cambio Tapas de tanque. No coincide el p, Prov. coloc. inodoro y tapa Falta adjunt

*  (2021) Albañileria / Pintura 
    + Reparacion de piso Oficina Rectoria PB., Pintura oficina rectoría.

*  (2021) Electricidad 
    + Prov. Inst. central telefonica, Nueva Linea electrica

*  (2021) Gas 
    + Restablecimiento de Gas

*  (2021) Incendio 
    + Reponer 2 matafuegos ABC de 5Kgs





## Mobiliario

*  (2023) : Escritorio 2, Mesa pupitre doble 30, Pizarrón 2, Silla escolar 62 

*  (2022) : Escritorio 3, Mesa pupitre doble 45, Pizarrón 3, Silla escolar 98 

*  (2021) : Banco largo comedor 50, Mesa usos múltiples 25 



