---
title: 'AVDA. RIESTRA 5030'
subtitle: 'EEM N° 04/21° - EPC N° 04 PROVINCIA DE TUCUMAN - CAIYJ CLUB LUGANO - JIN A (EPCJS 04/21°) (SEDE) - PI RIESTRA'
---

#
## Infraestructura

* 3er año 
    + sdf - Finalizado 
    + Finalizada el 19/3/2023 


* Plan mejora en   adecuacion   cocina , comedor ,  cubierta  y reparacion revoques y pintura en areas significativas + evaluacion estado polideportivo. 
    + mejora edilicia - Planificado 
    + Inicio de obra: 06/09/2024 






## Mantenimiento

*  (2023) Electricidad 
    + Seguridad para aula informática 2do piso

*  (2023) Gas 
    + Adecuación instalación de gas

*  (2022) Carpinterías 
    + Recambio de cerradura por vandalismo, Reemplazo de vidrios de puerta por vanda

*  (2022) Electricidad 
    + Recambio de 7 ventiladores de pared

*  (2021) Carpinterías 
    + Rep cerradura puerta aula 4ºx vandalismo, Reponer 2 cerraduras-En biblioteca, Colocar mástil fijo en fachada de Jardín

*  (2021) Cubiertas / Impermeabilizaciones 
    + Reparar canaletas en techo de chapa

*  (2021) Electricidad 
    + Reponer timbre de entrada y reloj recreo, Coloc purificador en sala jardin

*  (2021) Sanitarias 
    + reposición de inodoro roto x vandalismo.





## Mobiliario

*  (2023) : Escritorio 3, Mesa pupitre doble 45, Pizarrón 3, Silla escolar 93, NA 1 

*  (2022) : Armario 2, Escritorio 3, Mesa pupitre doble 48, Pizarrón 3, Silla escolar 99 

*  (2021) : Armario 4, Escritorio 6, Mesa inicial 4, Mesa pupitre doble 95, Pizarrón 3, Silla escolar 216 





## Seguridad

*  Espacios seguros: 1 - Estado: Finalizado 
    + Guardia física: NO



