---
title: 'AVDA. TTE. GRAL. DELLEPIANE 4750'
subtitle: 'JIC N° 02/13° - EPC N° 15 REPUBLICA ARGENTINA - CECEP N° 13 MARTIN MALHARRO'
---

#
## Infraestructura

* Adecuacion de instalacion electrica, cubiertas y carpinterias 
    + mejora edilicia - Planificado 
    + Inicio de obra: Sin fecha de inicio 






## Mantenimiento

*  (2023) Electricidad 
    + INSTALACION DE SISTEMA DE ALARMA, Remplazo de ventiladores.

*  (2023) Gas 
    + Reemplazo de dos estufas, REMPLAZO DE TERMOTANQUE

*  (2022) Albañileria / Pintura 
    + Coloc alambre de púa-Pintar carpinterías, Ejecución de contrapiso y carpeta

*  (2022) Electricidad 
    + Reemplazar 7 ventilaores, Reemplazo de 18 luces de emergencia,

*  (2022) Gas 
    + Adecuación instalación de gas

*  (2022) Incendio 
    + Reponer dos lanzas de bronce

*  (2022) Otros Servicios 
    + retiro de dos juegos

*  (2022) Sanitarias 
    + Prov y coloc.  inodoro en baño por vanda, Prov y coloc.  inodoro en baño

*  (2021) Calefaccion y Refrigeracion 
    + Colocar purificador de aire

*  (2021) Carpinterías 
    + Cambiar cerraduras aulas 1 y 2 x vandali, Coloc 2 pasadores-Cuarto bombas

*  (2021) Electricidad 
    + Coloc 10 tomas dobles-Direc,secretaria, Coloc. secamanos electrico

*  (2021) Incendio 
    + Coloc extintor A informat,BC laboratorio, Colocacion de hidrantes x vandalismo.

*  (2021) Otros Servicios 
    + nivelar superficie verde en patio jardin

*  (2021) Sanitarias 
    + Coloc canilla entre bebederos-Entrada, Colocar inodoro Bº V





## Mobiliario

*  (2023) : NA 1 

*  (2022) : Armario 4, Banco largo comedor 6, Escritorio 3, Juego de patio 1, Mesa pupitre doble 45, Mesa usos múltiples 3, Piso antigolpe para juegos 60, Pizarrón 12, Silla escolar 93 

*  (2021) : Armario 4 





## Seguridad

*  Espacios seguros: 3 - Estado: A ejecutar 
    + Guardia física: NO



