---
title: 'AVDA. RIVADAVIA 4950'
subtitle: 'ENS N°04 ESTANISLAO SEVERO ZEBALLOS - LICEO N° 02 AMANCIO ALCORTA'
---

#
## Infraestructura

* Creacion de un comedor 
    + Mejora Edilicia - En Obra 
    + Inicio de obra: 01/06/2023 - Avance: 14% - Fecha de finalización: 28/12/2023 


* Instalacion electrica completa, impermeabilizacion, restauracion de un sector de fachada 
    + Mejora Edilicia - Finalizado 
    + Finalizada el 13/9/2022 






## Mantenimiento

*  (2023) Albañileria / Pintura 
    + Reacondicionamiento para 7 aulas, Adicional por zocalos

*  (2023) Carpinterías 
    + Reacondicionamiento de reja

*  (2023) Electricidad 
    + Prov. Coloc nuevos teléfonos y nueva lín

*  (2023) Gas 
    + Adecuación según indicaciones de Metroga

*  (2022) Albañileria / Pintura 
    + Pintura SUM integral, Desmonte de pilar perimetro patio jardin, Pintura de carpinterias de SUM, Cambio solados y pintura en salas

*  (2022) Carpinterías 
    + Prov. y coloc. de rejas, Prov. Coloc. 7 rejas en puertas

*  (2022) Electricidad 
    + Reacondicionamiento de telefonia

*  (2022) Gas 
    + Reacondicionamiento de gas, Acondicionar instalación de gas

*  (2022) Incendio 
    + Reacondicionamiento del sistema incendio

*  (2021) Carpinterías 
    + Colocar rejas-Sala digital y balcones 1P

*  (2021) Sanitarias 
    + Recambio de cañeria de tanques





## Mobiliario

*  (2023) : Banco largo comedor 16, Escritorio 7, Mesa pupitre doble 105, Mesa usos múltiples 9, Pizarrón 7, Silla escolar 217 

*  (2022) : Escritorio 8, Mesa pupitre doble 128, Pizarrón 8, Silla escolar 264 

*  (2021) : Escritorio 8, Mesa inicial 4, Mesa pupitre doble 120, Pizarrón 8, Silla escolar 268 





## Seguridad

*  Espacios seguros: 2 - Estado: A confirmar 
    + Guardia física: NO



