---
title: 'AVDA. TTE. GRAL. DELLEPIANE Y AVDA. ESCALADA'
subtitle: 'ESC. DE COM. N° 06 AMERICA - EEM N° 01/13° MANUEL MUJICA LAINEZ - CAIYJ CLUB AMERICA'
---

#
## Infraestructura

* 3er año 
    + sdf - En Obra 
    + Inicio de obra: Sin fecha de inicio - Avance: 90% - Fecha de finalización: - 


* Construcción de 4 aulas modulares en steel frame, adecuaciones en: vivienda casero, sala profesores y preceptores. 
    + mejora edilicia - Licitación 
    + Inicio de obra: 01/07/2023 






## Mantenimiento

*  (2023) Calefaccion y Refrigeracion 
    + Reparar sistema de calefacción

*  (2023) Cubiertas / Impermeabilizaciones 
    + Impermeabilización de hall ingreso

*  (2023) Electricidad 
    + Instalar un sistema Alarma:, Prov.Coloc. luces de emergencia, Remplazo de ventiladores de pared.

*  (2023) Medios de elevación 
    + Adecuacion de ascensor

*  (2022) Calefaccion y Refrigeracion 
    + Prov. coloc. 11 placas Eco sol 900watt

*  (2022) Carpinterías 
    + Remplazo de 4 puertas y arreglo de las d

*  (2022) Cubiertas / Impermeabilizaciones 
    + IMPERMEABILIZACION DE AZOTEA, Remplazo de chapas en hall de entrada

*  (2022) Gas 
    + Reemplazo del tanque de expansión

*  (2022) Medios de elevación 
    + Adecuacion de ascensor

*  (2022) Sanitarias 
    + Puesta en marcha de 2 baños PB y 2 en PA, Remplazar inodoro corto capea por vandal

*  (2021) Gas 
    + Readecuacion instalacion completa de gas

*  (2021) Incendio 
    + Reponer hidrante por vandalismo





## Mobiliario

*  (2023) : Escritorio 3, Mesa pupitre doble 45, Pizarrón 3, Silla escolar 93 

*  (2022) : Escritorio 4, Mesa pupitre doble 76, Pizarrón 4, Silla escolar 156 

*  (2021) : Escritorio 4, Mesa pupitre doble 60, Pizarrón 4, Silla escolar 124 





## Seguridad

*  Espacios seguros: 1 - Estado: En ejecución 
    + Guardia física: NO

*  Espacios seguros: 1 - Estado: Finalizado 
    + Guardia física: NO



