---
title: 'GRAL. MARTIN DE GAINZA 1050'
subtitle: 'ESC. TEC. N° 09 ING. LUIS A. HUERGO - CAIYJ CLUB HUERGO'
---

#
## Infraestructura

* Impermeabilización de las azoteas, cubierta tipo shed de los talleres y
Laboratorios. instalaciones eléctrica, sanitaria, contra incendio, termomecánica y la reparación –
Puesta en norma del ascensor. 
    + mejora edilicia - En Obra 
    + Inicio de obra: 19/01/2023 - Avance: 70% - Fecha de finalización: 28/2/24 


* NA 
    + mejora edilicia - Planificado 
    + Inicio de obra: Sin fecha de inicio 


* Imperbeabilizacion de un sector de azotea 
    + mejora edilicia - Finalizado 
    + Finalizada el - 






## Mantenimiento

*  (2023) Calefaccion y Refrigeracion 
    + Rep calefactores de taller-laboratorio

*  (2023) Carpinterías 
    + Prov y coloc cortinas rollers blackouts

*  (2023) Electricidad 
    + INSTALACION EN ESPACIOS SEGUROS

*  (2023) Sanitarias 
    + Colocar tablas de inodoros y matafuegos

*  (2022) Albañileria / Pintura 
    + Instalacion de agua en laboratorio, Aulas del futuro aula 2,7,12,22

*  (2022) Carpinterías 
    + Reparación de las ventanas de las aulas

*  (2022) Electricidad 
    + Cambio paneles LED, tableros, Arreglos en placas de LED-Aulas, Adecuar inst eléctrica-Laboratorio

*  (2022) Gas 
    + Reacondicionamiento reguladores gas, Readecuar instalación de gas-Laboratorio

*  (2022) Sanitarias 
    + Cambio del termotanque de la cocina

*  (2021) Calefaccion y Refrigeracion 
    + Adicional-Puesta en marcha-Calefactores

*  (2021) Electricidad 
    + Instalación de 2 nuevos motores

*  (2021) Gas 
    + Adecuacion inst de gas, Adecuación de los equipos de calefacción





## Mobiliario

*  (2023) : Escritorio 5, Mesa pupitre doble 75, Silla escolar 155 

*  (2022) : Escritorio 7, Mesa pupitre doble 90, Pizarrón 6, Silla escolar 214 





## Seguridad

*  Espacios seguros: 2 - Estado: Suspendida ejecución 
    + Guardia física: NO



