---
title: 'SAN BLAS 5387'
subtitle: 'ESC. DE COM. N° 30 DR. ESTEBAN AGUSTIN GASCON'
---

#


## Mobiliario

*  (2023) : Escritorio 3, Mesa pupitre doble 45, Pizarrón 3, Silla escolar 93 

*  (2021) : Escritorio 2, Mesa pupitre doble 30, Silla escolar 62 





## Mantenimiento

*  (2023) Albañileria / Pintura 
    + 3 aulas del Futuro, Construcción de vereda en acceso parque, provisión e instalación de ventiladores

*  (2023) Electricidad 
    + Cambio de artefactos electrico, Adecuación electrica en preceptoria PB/P

*  (2023) Sanitarias 
    + Colocación de tanque de reserva

*  (2022) Albañileria / Pintura 
    + Rep solado y cielorraso-Laboratorio 2

*  (2022) Carpinterías 
    + Colocación de film de seguridad es prece

*  (2022) Electricidad 
    + Adecuación eléctrica del DOE

*  (2022) Incendio 
    + Colocar un matafuego en secretaría, Colocacion matafuegos en sala de docente, Colocar un matafuego

*  (2022) Sanitarias 
    + Colocacion inodoro B discap.

*  (2021) Albañileria / Pintura 
    + Restauración-Consolidacion de aula en PB, Pintura de frisos en patio de planta baj

*  (2021) Carpinterías 
    + Cambio de carpinteria S.Digital y comput, cambio de persianas en planta baja y pri

*  (2021) Sanitarias 
    + Rep de caño de agua en Patio Exterior, Reemplazo de termotanque casa casera



