---
title: 'AVDA. ALVAREZ JONTE 5075'
subtitle: 'ESC. DE COM. N° 33 MAIPU'
---

#
## Infraestructura

* Instalacion electrica completa 
    + Mejora Edilicia - Finalizado 
    + Finalizada el 31/1/2023 






## Mantenimiento

*  (2023) Albañileria / Pintura 
    + Reparacion de revoques, cielorraso, Secundarias del Futuro 2023, Solado oficina biblioteca

*  (2023) Electricidad 
    + Colocacion Sist Alarma Espacio Seguro, Colocacion de 10 placas Led en Aulas

*  (2023) Sanitarias 
    + Tanques de Reserva

*  (2022) Calefaccion y Refrigeracion 
    + Seis estufas tiro ballanceado

*  (2022) Gas 
    + Readecuación Inst. Gas sector Bermudez

*  (2021) Albañileria / Pintura 
    + Albañileria/Pintura en Secretaria/Precep, Rep revoques y pintura en Baños

*  (2021) Carpinterías 
    + Protecciones estufas tiro balanceado, Proteciones baranda escalera, Reparacion puertas madera acceso





## Mobiliario

*  (2023) : Escritorio 2, Mesa pupitre doble 30, Pizarrón 2, Silla escolar 62 

*  (2022) : Escritorio 2, Mesa pupitre doble 52, Pizarrón 2, Silla escolar 107 

*  (2021) : Banco largo comedor 38, Escritorio 7, Mesa pupitre doble 75, Pizarrón 3, Silla escolar 154 



