---
title: 'GRAL. URQUIZA 277'
subtitle: 'ENS N°02 EN LENGUAS VIVAS MARIANO ACOSTA - IES MARIANO ACOSTA - ESEA EN DANZA RAMICONE CURSO VOCACIONAL DE FOLKLORE N° 06'
---

#


## Seguridad

*  Espacios seguros: 1 - Estado: A confirmar 
    + Guardia física: NO





## Mobiliario

*  (2023) : Armario 6, Escritorio 5, Mesa inicial 9, Mesa pupitre doble 45, Pizarrón 3, Silla escolar 147 

*  (2022) : Armario 4, Escritorio 6, Mesa usos múltiples 1 

*  (2021) : Armario 4, Escritorio 4, Mesa pupitre doble 40, Silla escolar 84 





## Mantenimiento

*  (2023) Albañileria / Pintura 
    + Realizar 3 aulas del futuro, Renovacion de sector afectado incendio

*  (2023) Electricidad 
    + Realizacion de espacio digital, Reemplazar 21 ventiladores

*  (2023) Gas 
    + Puesta a normativa de gas

*  (2023) Medios de elevación 
    + Prov e inst de contactora en ascensor

*  (2022) Calefaccion y Refrigeracion 
    + Acondicionar sistema de caldera, Instalación de placas calefactoras

*  (2022) Cubiertas / Impermeabilizaciones 
    + Imimpermeabilizacion de azotea, Coloc placas antihumedad aula L154 La in

*  (2022) Gas 
    + CAMBIO TT CASA CASERA

*  (2022) Otros Servicios 
    + COLOCAR PURIFICADORES DE AIRE

*  (2021) Calefaccion y Refrigeracion 
    + Inst 3 placas calefactoras aulas jardin, Corto el motor de 16 ventiladores pared

*  (2021) Incendio 
    + Prov 2 matafuegos PVP X 5KG por fallas

*  (2021) Medios de elevación 
    + Puesta en marcha de ascensores 2 y 3

*  (2021) Sanitarias 
    + Reparar puertas de cubiculos de baños, Refacción de baño de niñas - Patio



