---
title: 'LIBERTAD 581'
subtitle: 'Sup Inicial I A - JIN A (EPCJS 07/01°) - EPA N° 07 PRESIDENTE ROCA - EPC N° 07 PRESIDENTE ROCA'
---

#
## Infraestructura

* Freno de deterioro (escuela patrimoniada): restauración de las fachadas interiores (patios). reparación de los revoques en paramentos interiores (circulaciones) afectados por humedad
De cimientos. reparación de cielorrasos dañados por humedad.  restauracion de zócalos perimetral de marmol, solados, escaleras principales, carpinterias y herrerias. reacondicionamiento de aulas de jardín de infante. colocacion de una rampa para dar accesibilidad. adecuación de la instalación eléctrica de baja tensión y muy baja tensión, en planta baja y en
Primer piso 
    + mejora edilicia - Finalizado 
    + Finalizada el 31/5/2023 


* Segunda etapa freno de deterioro (escuela patrimoniada): restauración de las fachadas interiores (patios). reparación de los revoques en paramentos interiores (circulaciones) afectados por humedad
De cimientos. reparación de cielorrasos dañados por humedad.  restauracion de zócalos perimetral de marmol, solados, escaleras principales, carpinterias y herrerias. reacondicionamiento de aulas de jardín de infante. colocacion de una rampa para dar accesibilidad. adecuación de la instalación eléctrica de baja tensión y muy baja tensión, en planta baja y en
Primer piso 
    + mejora edilicia - Planificado 
    + Inicio de obra: 9/5/2025 






## Mantenimiento

*  (2023) Albañileria / Pintura 
    + Reemplazo de solado en aulas

*  (2023) Sanitarias 
    + Reparación de colector tanque de agua

*  (2022) Electricidad 
    + Colocar ventiladores en aulas, Reemplazo de Termotanques

*  (2022) Sanitarias 
    + Prov. Coloc. 1 Inodoro vandalizado

*  (2021) Albañileria / Pintura 
    + Provision y colocacion parrilla movil, Colocar placas en carpinterías 1erPiso





## Mobiliario

*  (2023) : Armario 1, Pizarrón 14 

*  (2022) : Armario 2, Mesa pupitre doble 52, Pizarrón 14, Silla escolar 106 

*  (2021) : Armario 4, Mesa inicial 6, Silla escolar 60 



