---
title: 'AVDA. INTENDENTE FRANCISCO RABANAL 1549'
subtitle: 'ESC. TEC.  N° 33 F. MAESTRANZA DEL PLUMERILLO - CAIYJ CLUB POMPEYA'
---

#


## Seguridad

*  Espacios seguros: 2 - Estado: Finalizado 
    + Guardia física: SI





## Mobiliario

*  (2023) : Escritorio 1, Mesa pupitre doble 15, Pizarrón 1, Silla escolar 31 

*  (2022) : Escritorio 4, Mesa pupitre doble 66, Pizarrón 4, Silla escolar 136 

*  (2021) : Escritorio 9, Mesa pupitre doble 75, Pizarrón 5, Silla escolar 207 





## Mantenimiento

*  (2023) Albañileria / Pintura 
    + SDF 2023. Adecuación, 1 aula

*  (2023) Cubiertas / Impermeabilizaciones 
    + Filtración Laboratorio

*  (2023) Electricidad 
    + Espacios seguros

*  (2023) Sanitarias 
    + Adecuación bajada Sanitaria, Sanitarios, Sanitaria

*  (2022) Calefaccion y Refrigeracion 
    + Reemplazo Estufas Rabanal 1549 (Técnica)

*  (2022) Electricidad 
    + Adecuación Tablero Buffet

*  (2022) Incendio 
    + Cambio de Mangueras

*  (2022) Sanitarias 
    + Rep. /Inst. de Automatico de Bomba, Rotura inodoro por vandalismo, Desvío salida cloacal provisoria

*  (2021) Albañileria / Pintura 
    + Reparacion de estructuras y otros, Adicionales Reparación cubierta, Fijacion de placas de cielorraso

*  (2021) Calefaccion y Refrigeracion 
    + Reponer cañeria split por vandalismo, Instalar 10 splits

*  (2021) Carpinterías 
    + Guardaganado,pileta,conexion pluvial, Elevación rejas y colocación cocertina

*  (2021) Incendio 
    + Reposición de 2 lanzas por Vandalismo, Reemplazo de 7 extintores



