---
title: 'PICO 2689'
subtitle: 'JIC N° 05/10° PABLO PICASSO - EPA N° 15 PROVINCIA DE SANTA FE - EPC N° 15 PROVINCIA DE SANTA FE'
---

#
## Infraestructura

* Plan mejora edif cacciatore adecuacion de patio+ carpinteria  + inst electrica+ instalacion termomecanica -   cubierta y pintura en areas significativas + polideportivo en terreno lindero. ver fachada ladrillos 
    + mejora edilicia - Planificado 
    + Inicio de obra: 1/9/2023 






## Mantenimiento

*  (2023) Electricidad 
    + INSTALACION EN ESPACIOS SEGUROS

*  (2022) Calefaccion y Refrigeracion 
    + PROVEER CALEFACCIÓN A 2 AULAS

*  (2022) Carpinterías 
    + Provision reja jardín y columnas gim, CAMBIO DE CERRADURAS ACCESO

*  (2022) Medios de elevación 
    + Actualización control ascensor

*  (2021) Calefaccion y Refrigeracion 
    + Reparación en calefaccion y tablero

*  (2021) Cubiertas / Impermeabilizaciones 
    + cambio parcial de membrana





## Mobiliario

*  (2022) : Escritorio 6, Mesa pupitre doble 90, Pizarrón 14, Silla escolar 186 

*  (2021) : Mesa inicial 5, Silla escolar 30 





## Seguridad

*  Espacios seguros: 1 - Estado: Finalizado 
    + Guardia física: NO



