---
title: 'ACASSUSO 5860'
subtitle: 'ESC. DE COM.  N° 32 JOSE LEON SUAREZ [S]'
---

#
## Infraestructura

* Sede: sanitarios a nuevos, impermeabilizaciones, pintura (20mm), reparaciones varias, adecuacion de carpinterias, ie completa y cambio e canaletas y sesagues pluviales.  anexo: solado de los balcones, bicicletero, cortinas roller, adecuacion en sala de musica, pintura y arreglo de fachada, reparacion de carpinterias, patio: demarcacion de canchas, pintura y cerco de alambre. refuncionalizacion de sala de tanque. ie completa. 
    + mejora edilicia - Licitación 
    + Inicio de obra: 29/1/2024 


* Sede: sanitarios a nuevos, impermeabilizaciones, pintura (20mm), reparaciones varias, adecuacion de carpinterias, ie completa y cambio e canaletas y sesagues pluviales.  anexo: solado de los balcones, bicicletero, cortinas roller, adecuacion en sala de musica, pintura y arreglo de fachada, reparacion de carpinterias, patio: demarcacion de canchas, pintura y cerco de alambre. refuncionalizacion de sala de tanque. ie completa. 
    + mejora edilicia - Licitación 
    + Inicio de obra: 29/1/2024 






## Mantenimiento

*  (2023) Carpinterías 
    + Instalar pasamanos y barandas.Modificar





## Mobiliario

*  (2023) : Escritorio 3, Mesa pupitre doble 45, Pizarrón 3, Silla escolar 93 

*  (2022) : Escritorio 3, Mesa pupitre doble 45, Pizarrón 3, Silla escolar 93 



