---
title: 'CORRALES 3420 - CORRALES 3420 / 3450'
subtitle: 'JIC N° 03/19° - EPC N° 17 GASPAR LUCILO BENAVENTO - CENOF CENTRO CORRALES - PI BICHITO DE LUZ - EPC N° 18 SAN JUAN BAUTISTA DE LA SALLE - EPA N° 18 SAN JUAN BAUTISTA DE LA SALLE - JII N° 07/19° - CAIYJ CLUB DE JOVENES SOLDATI'
---

#


## Seguridad

*  Espacios seguros: 2 - Estado: Finalizado 
    + Guardia física: NO

*  Espacios seguros: 2 - Estado: Finalizado 
    + Guardia física: NO





## Mobiliario

*  (2023) : Escritorio 10, Mesa pupitre doble 150, Silla escolar 300, NA 2 

*  (2022) : Armario 4, Escritorio 2, Mesa pupitre doble 45, Pizarrón 11, Silla escolar 90 

*  (2021) : Banco largo comedor 140, Mesa inicial 10, Mesa pupitre doble 50, Mesa usos múltiples 70, Pizarrón 5, Silla escolar 160 





## Mantenimiento

*  (2023) Carpinterías 
    + Instalar 11 pizarrones en aulas

*  (2023) Electricidad 
    + Cotización de aulas seguras.

*  (2023) Sanitarias 
    + Reponer inodoro destruido por vandalismo

*  (2022) Albañileria / Pintura 
    + Cambio pisos ceramicos pisos Sum

*  (2022) Carpinterías 
    + Colocar vidrios en puerta balcón por van, Provisión de vidrios vandalizados

*  (2022) Incendio 
    + Reponerr 4 lanzas plasticas de incendio

*  (2022) Sanitarias 
    + Solicito cambio de termotanque en cocina, Mochila Ferrum para B° Discapacitados

*  (2021) Albañileria / Pintura 
    + Refacciones alimentacion agua y sanit.

*  (2021) Calefaccion y Refrigeracion 
    + Reposicion de 3 estufas

*  (2021) Carpinterías 
    + Proveer, instalar cerradura en PB x vand, Prov, instalacion de cerradura x vandali

*  (2021) Electricidad 
    + Cambio portero electrico de entrada, Instalacion 1 AA° en aula

*  (2021) Incendio 
    + Provision matafuegos



