---
title: 'VALDENEGRO 3523'
subtitle: 'ESC. DE COM. N° 28 ABRAHAM LINCOLN - ESC. DE COM. N° 15 DRA. CECILIA GRIERSON'
---

#
## Infraestructura

* Intervención completa de fachadas de valdenegro, incluidas las del contrafrente sobre la calle miller y las caras interiores no contempladas en obra de ampliación nes, patios, reparación de humedades en mamposterías, acondicionamiento de patios, reparación de carpinterías, acondicionamiento de sanitarios de docentes, acondicionamiento de instalación de provisión de agua y reparacion de tanques ( sistema integral para ambas escuelas), revisión de cubiertas e instalación pluvial.
En media pintura general de los sectores requeridos que no hayan sido intervenidos por la obra de ampliación ni por sdf ejecutada por dgmesc.
En primaria pintura integral, acondicionamiento de instalación eléctrica y accesibilidad plena.
 
    + mejora edilicia - Planificado 
    + Inicio de obra: 15/04/2024 
    + Plan de obras 2024 - 2027 






## Mantenimiento

*  (2022) Calefaccion y Refrigeracion 
    + Cambiar quemador y modificar chimenea





## Mobiliario

*  (2023) : Escritorio 2, Mesa pupitre doble 30, Pizarrón 2, Silla escolar 62 

*  (2022) : Escritorio 3, Mesa pupitre doble 45, Pizarrón 3, Silla escolar 93 

*  (2021) : Escritorio 3, Mesa pupitre doble 45, Pizarrón 3, Silla escolar 93 





## Seguridad

*  Espacios seguros: 2 - Estado: En ejecución 
    + Guardia física: NO



