---
title: 'AVDA. ALVAREZ JONTE 4651'
subtitle: 'EPC N° 03 MONTE CASTRO - JINA(EPCJS03/18°)[S]LA CALESITA DON JOSE - EPA N° 03 MONTE CASTRO'
---

#
## Infraestructura

* Plan mejora cubiertacon impermeabilizacion, pintura y reparacion de revoques y cielorrasos, acondicionamiento de instalacion electrica y calefaccion 
    + mejora edilicia - Planificado 
    + Inicio de obra: Sin fecha de inicio 


* Cubierta, pintura, cielorrasos, revoques, electrica, calefaccion 
    + mejora edilicia - Planificado 
    + Inicio de obra: 28/12/2024 






## Mantenimiento

*  (2023) Electricidad 
    + provision de 2 ventiladores para direcci

*  (2022) Albañileria / Pintura 
    + Adecuación de escalera en sala de música

*  (2022) Carpinterías 
    + Cambiador para bebes

*  (2022) Electricidad 
    + Adecuar instalacion electrica, Tendido electrico carros de computacion, Reemplazo de ventiladores en aulas de ni, Portero eléctrico con visor

*  (2022) Otros Servicios 
    + Colocación  de un matafuegos faltante

*  (2021) Calefaccion y Refrigeracion 
    + Placas refractarias para horno ceramico, Colocación de purificadores

*  (2021) Sanitarias 
    + 6 bajadas pluviales





## Mobiliario

*  (2023) : Silla escolar 60, NA 1 

*  (2022) : Banco largo comedor 11, Mesa pupitre doble 30, Mesa usos múltiples 17, Silla escolar 60 



