---
title: 'AVDA. SAN PEDRITO 1415'
subtitle: 'EPC N° 04 BENJAMIN ZORRILLA - JIC N° 02/11°'
---

#
## Infraestructura

* Ejecución ampliación y remodelación jic (tal como esta previsto en el proyecto). ejecución de solados patios descubiertos los que deberían incluir el sector que hoy se encuentra con terreno absorbente, desnivelado y con cascotes. construcción de un semicubierto para utilizar como gimnasio. trabajos en muros perimetrales ya que al ser terreno de relleno se producen desplazamientos constantemente, sumado a la rotura de llos mismo por los arboles. idem rejas perimetrales. pintura de herrerías (parasoles, protecciones y carpinterías de chapa y hierro ángulo). puesta en marcha sistema de ventilación (posee los conductos pero solo funciona la calefacción, al ser muy vidriado el edificio los espacios comunes se transforman en grandes hornos, y las aulas poseen poca ventilación al ser de apertura de proyección) 
    + mejora edilicia - Planificado 
    + Inicio de obra: 6/12/2024 






## Mantenimiento

*  (2022) Incendio 
    + Provision de matafuego en cocina, Instalación de detectores

*  (2022) Sanitarias 
    + Acondicionamiento de acceso a tanque

*  (2021) Albañileria / Pintura 
    + reemplazo de cielorraso en varios sector

*  (2021) Electricidad 
    + Tendido alimentacion electrica de jardin

*  (2021) Gas 
    + Reemplazo termotanque sala auxiliares

*  (2021) Medios de elevación 
    + puesta en norma del ascensor





## Mobiliario

*  (2021) : Pizarrón 2 



