---
title: 'ESMERALDA 285'
subtitle: 'ISFA [A 3] - ESC. SUPERIOR DE EDUCACIÓN ARTÍSTICA EN DANZA AÍDA VICTORIA MASTRAZZI'
---

#
## Infraestructura

* Restauracion de fachadas, refacciones generales de cielorrasos, pisos, sala
De cooperadora y sala docente , inst eléctrica, sanitarios 
    + Mejora Edilicia - En Obra 
    + Inicio de obra: 20/1/2023 - Avance: 1% - Plazo: 310 



## Mobiliario

*  (2023) : Escritorio 2, Locker 15, Mesa pupitre doble 30, Pizarrón 2, Silla escolar 62 

*  (2022) : Escritorio 2, Mesa pupitre doble 32, Pizarrón 2, Silla escolar 64, Varios 2 

*  (2021) : Escritorio 2, Mesa pupitre doble 30, Pizarrón 2, Silla escolar 62 





## Mantenimiento

*  (2022) Albañileria / Pintura 
    + Adecuación SDF- 2 aulas

*  (2022) Electricidad 
    + Ejecución de Tomacorrientes de Uso Gener

*  (2022) Medios de elevación 
    + Puesta en Normativa de Ascensor

*  (2022) Sanitarias 
    + Recambio de inodoro por rotura

*  (2021) Albañileria / Pintura 
    + Acondicionamiento aula archivo, Remodelación de dos aulas-SDF

*  (2021) Calefaccion y Refrigeracion 
    + Instalar 1 purificador en Biología

*  (2021) Carpinterías 
    + Cambio de puerta cortafuegos S.Maquinas

*  (2021) Electricidad 
    + Prov,coloc tarima, inst electrica,pintur, Instalar 7 purificadores






