---
title: 'ARCAMENDIA 743'
subtitle: 'ENS N° 05 GRAL.  M. M. DE GÜEMES (SEDE) - LICEO COM. N° 03 JOSE MANUEL ESTRADA'
---

#
## Infraestructura

* Instalacion electrica completa, impermeabilizacion, restauracion de un sector de fachada 
    + mejora edilicia - En Obra 
    + Inicio de obra: 23/11/2021 - Avance: 80% - Fecha de finalización: neutralizada 






## Mantenimiento

*  (2023) Albañileria / Pintura 
    + Pintura en pasillos y alumnos, PINTURA INTEGRAL Y VARIOS

*  (2023) Calefaccion y Refrigeracion 
    + Estufa casera

*  (2023) Carpinterías 
    + Colocar picaportes y cerraduras, Reparación de ventana aula planta alta

*  (2023) Incendio 
    + Recarga de 3 extintores accionados

*  (2022) Albañileria / Pintura 
    + Cambio de piso vinilico, pintura aula

*  (2021) Carpinterías 
    + Fabricación y colocación rampa discapaci

*  (2021) Gas 
    + Remplazar el artefacto cocina





## Mobiliario

*  (2023) : Escritorio 5, Mesa pupitre doble 75, Pizarrón 5, Silla escolar 155 

*  (2022) : Escritorio 5, Mesa pupitre doble 75, Pizarrón 5, Silla escolar 155 

*  (2021) : Escritorio 6, Mesa pupitre doble 90, Pizarrón 10, Silla escolar 186 





## Seguridad

*  Espacios seguros: 2 - Estado: Finalizado 
    + Guardia física: NO



