---
title: 'AVDA. CALLAO 450'
subtitle: 'ENS N° 09 DOMINGO FAUSTINO SARMIENTO - LICEO N° 07 DOMINGO FAUSTINO SARMIENTO'
---

#
## Infraestructura

* 2do año 
    + SDF - En Obra 
    + Inicio de obra: 22/02/2023 - Avance: 50% - Plazo: 60 días 






## Mantenimiento

*  (2022) Medios de elevación 
    + reparacion ascensor

*  (2022) Sanitarias 
    + Colocación de 3 tanques cisterna

*  (2021) Albañileria / Pintura 
    + SDF - 2021

*  (2021) Calefaccion y Refrigeracion 
    + Placas calefactoras dirección de Jardín, 21 ventiladores de pared de 20

*  (2021) Carpinterías 
    + Refacción de todas las ventanas, Colocación cinta reflectora en escalones

*  (2021) Electricidad 
    + Bocas de electricidad para purificadores

*  (2021) Gas 
    + Ttermotanque eléctrico casa casera

*  (2021) Incendio 
    + Reposición de sistema contra incendio, Provisión de 3 matafuegos PVP x 5kg

*  (2021) Otros Servicios 
    + 4 AULAS SECUNDARIAS DEL FUTURO





## Mobiliario

*  (2023) : Escritorio 1, Mesa pupitre doble 15, Pizarrón 1, Silla escolar 31 

*  (2022) : Armario 20, Escritorio 8, Mesa pupitre doble 120, Pizarrón 10, Silla escolar 248 

*  (2021) : Armario 4, Escritorio 4, Mesa pupitre doble 90, Pizarrón 4, Silla escolar 60 



