---
title: 'BRAUN MENENDEZ 260'
subtitle: 'Sup Inicial II A - EPC N° 08 CARLOS DELLA PENNA - JIC N° 02/04° CARLOS DELLA PENNA - ESC. DE MUSICA N° 01'
---

#
## Infraestructura

* Impermeabilización de azoteas. Reparación de carpinterías existentes del primer piso con problemas de oxidación. Pintura de rejas en planta alta, nivel a y b. Reparaciones en fachadas de patio interno en planta baja:pintura y limpieza. Intervención de solados – mal estado. Demolición de mesadas en dos aulas del nivel inicial. Provisión y colocación de bicicletero en el acceso del edificio. Trabajos varios de jardinería en canteros. Accesibilidad: provisión y colocación de ascensor para comunicar la planta baja y primer piso. Ejecución de rampa para salvar un desnivel entre primer piso y la azotea. 
    + Mejora Edilicia - Planificado 
    + Inicio de obra: Sin fecha de inicio 






## Mantenimiento

*  (2023) Electricidad 
    + Instalación de espacios seguro

*  (2023) Incendio 
    + Provisión/Colocación extintor ABC 5kg

*  (2021) Albañileria / Pintura 
    + Cambio de solado en 7 aulas

*  (2021) Carpinterías 
    + Cambiar puertas de balcon

*  (2021) Electricidad 
    + Prov,coloc 9 artef de luz-Casa casero. E

*  (2021) Gas 
    + Regularizar inst de gas, Red y artefactos de gas en cocina





## Mobiliario

*  (2022) : Escritorio 3, Mesa inicial 10, Mesa pupitre doble 48, Pizarrón 15, Silla escolar 156 





## Seguridad

*  Espacios seguros: 1 - Estado: En ejecución 
    + Guardia física: NO



