---
title: 'MOLDES 1854'
subtitle: 'Superv.Educ.Prim. Zona E Región IX-DE10 - EPC N° 03 ESTEBAN ECHEVERRIA'
---

#
## Infraestructura

* Sanitarios, patios, cubierta (impermeabilizacion y arreglos de cubierta parabolica), cielorrasos, puesta en valor de escalera y aulas. Ie completa. Supervision (patios, solados, carpinterias, sanitarios y sellado de lucarnas). 
    + Mejora Edilicia - En Proyecto 
    + Inicio de obra: 9/2/2024 






## Mantenimiento

*  (2023) Albañileria / Pintura 
    + Pintura del gimnasio, Reparación de muros y pintura

*  (2023) Gas 
    + Inst.5 protecciones mecánicas en estufas

*  (2023) Saneamiento 
    + Prov.Coloc red anti palomas patio acceso, Prov.Coloc red anti palomas en Sum

*  (2023) Sanitarias 
    + Nuevo red clocal entre cámara, Reparación del tramo de cañería hall

*  (2021) Cubiertas / Impermeabilizaciones 
    + Impermeabilización de patios

*  (2021) Electricidad 
    + Reparación de timbre de recreos





## Mobiliario

*  (2022) : Armario 6, Escritorio 8, Mesa pupitre doble 50, Pizarrón 8, Silla escolar 108 



