---
title: 'AVDA. RIVADAVIA 6065 - YERBAL 1548'
subtitle: 'EPA N° 04 PRES. DR. ARTURO UMBERTO ILLIA - EPC N° 04 PRES. DR. ARTURO UMBERTO ILLIA - JIC N° 03/07° LA PORTEÑA'
---

#


## Mobiliario

*  (2022) : Armario 4, Mesa pupitre doble 40, Pizarrón 7, Silla escolar 80 

*  (2021) : Banco largo comedor 40, Mesa pupitre doble 35, Mesa usos múltiples 20, Silla escolar 70 





## Mantenimiento

*  (2022) Albañileria / Pintura 
    + Impermeabilización azotea tanque

*  (2022) Calefaccion y Refrigeracion 
    + Colocar AºAº sala de plastica 3er piso

*  (2022) Carpinterías 
    + Prov. coloc. pasamanos

*  (2022) Electricidad 
    + Cambio ubicación toma primaria Edesur, Recambio de artefactos de luz

*  (2022) Sanitarias 
    + Prov. coloc. termotanque electrico, Cambio de tanque de expansión

*  (2021) Albañileria / Pintura 
    + Reacondicionamiento por filtraciones, Pintura pared medianera patio

*  (2021) Electricidad 
    + Colocar aires acondicionados, Reandicionamiento electrico de tablero -, Reacondicionamiento tableros - ETAPA 2, Recambio de termotanque en sala de máqui



