---
title: 'LAVALLE 1681'
subtitle: 'ESC. TEC. N° 19 ALEJANDRO VOLTA'
---

#
## Infraestructura

* Mejora edilicia, instalacion electrica completa 
    + mejora edilicia - Finalizado 
    + Finalizada el 30/9/2023 






## Mantenimiento

*  (2023) Carpinterías 
    + Prov y coloc cortinas aulas del futuro

*  (2023) Electricidad 
    + INSTALACION EN ESPACIOS SEGUROS

*  (2022) Electricidad 
    + Reemplazo de Ventiladores

*  (2022) Otros Servicios 
    + Limpiar espacios utilizados para obra

*  (2021) Carpinterías 
    + Prov,coloc paños de ventanales 1º,2ºP, Prov,cambio 10 ventanas PB, Reempazo de carpinterías-Aulas

*  (2021) Electricidad 
    + Instalar purificador y boca de electric, Coloc 9 purificadores en aulas





## Mobiliario

*  (2023) : Escritorio 2, Mesa pupitre doble 30, Pizarrón 2, Silla escolar 62 

*  (2022) : Escritorio 3, Mesa pupitre doble 45, Pizarrón 3, Silla escolar 93 

*  (2021) : Escritorio 3, Mesa pupitre doble 45, Pizarrón 3, Silla escolar 93 





## Seguridad

*  Espacios seguros: 3 - Estado: En ejecución 
    + Guardia física: NO



