---
title: 'AVDA. GRAL. FERNANDEZ DE LA CRUZ 3605'
subtitle: 'ESC. DE EDUC. MEDIA Nº 05 DE 19 E.REINGRESO'
---

#
## Infraestructura

* Conexion de instalacion de gas (medidor y conexion)+ habilitacion y puesta en marcha sistema de calefaccion 
    + Mejora Edilicia - En Obra 
    + Inicio de obra: Sin fecha de inicio - Avance: 0% - Plazo: 60 días 






## Mantenimiento

*  (2023) Albañileria / Pintura 
    + 2 aulas del futuro - Primer Piso

*  (2023) Electricidad 
    + INSTALACION EN ESPACIOS SEGUROS

*  (2022) Carpinterías 
    + Provisión y colocación de vidrios por va, Red antipalomas en PB y 1erPiso

*  (2022) Incendio 
    + Adecuacion instalacion contra incendio

*  (2022) Sanitarias 
    + Prov. coloc. de inodoro vandalizado., Prov. Coloc. de inodoro, vidrios, barral

*  (2021) Carpinterías 
    + Prov. e inst. pasadores puertas emergenc





## Mobiliario

*  (2023) : Escritorio 2, Mesa pupitre doble 30, Pizarrón 2, Silla escolar 62 

*  (2022) : Escritorio 2, Mesa pupitre doble 33, Pizarrón 2, Silla escolar 68 

*  (2021) : Escritorio 2, Mesa pupitre doble 30, Pizarrón 2, Silla escolar 62 



