---
title: 'GRAL. GREGORIO ARAOZ DE LAMADRID 499'
subtitle: 'EPC N° 10 GRAL. ARAOZ DE LAMADRID'
---

#
## Infraestructura

* Historica. Fachada, patio, instalacion electrica,carpinterias,sanitarios y pintura 
    + Mejora Edilicia - Planificado 
    + Inicio de obra: NA 






## Mantenimiento

*  (2023) Electricidad 
    + Instalación tablero de luces emergencia

*  (2022) Albañileria / Pintura 
    + Reparación en cocina, Presupuesto pintira en direccion

*  (2022) Carpinterías 
    + Reemplazo carpinteria a patio., Soporte para proyector en comedor

*  (2022) Electricidad 
    + Agregado de tomas, extensión de ménsula

*  (2022) Gas 
    + Adecuar instalación de gas a normativa

*  (2022) Sanitarias 
    + Realizar cámara nueva en sector cocina, Reposición de inodoro en baño nenas

*  (2021) Albañileria / Pintura 
    + Reparar fachada, Pintura exterior de fachadas frente

*  (2021) Cubiertas / Impermeabilizaciones 
    + Impermeabilizar azotea

*  (2021) Gas 
    + Adecuación de Inst de Gas





## Mobiliario

*  (2022) : Armario 6, Banco largo comedor 16, Escritorio 1, Mesa pupitre doble 15, Mesa usos múltiples 8, Pizarrón 28, Silla escolar 30 



