---
title: 'MARIANO ACOSTA 2976'
subtitle: 'EPC N° 21 GUILLERMO JOSE BARROS - CENS N° 71 - CAIYJ CLUB DE JOVENES FATIMA'
---

#
## Infraestructura

* Mejora edilicia, reparacion de cubiertas, adecuacion de instalaciones sanitarias, electricas y pluvial. reparacion de muros y pintura integral 
    + mejora edilicia - Planificado 
    + Inicio de obra: Sin fecha de inicio 






## Mantenimiento

*  (2023) Carpinterías 
    + Prov. y coloc. vidrios rotos en sala por

*  (2023) Electricidad 
    + Prov e Inst. 2 ventiladores en aula

*  (2022) Carpinterías 
    + Colocacion de Pizarrones en aulas

*  (2022) Electricidad 
    + Proveer e instalar ventilador en aula 5

*  (2022) Gas 
    + provision y colocacion termotanque

*  (2022) Sanitarias 
    + Provisión de tapa de inspección cloacal

*  (2021) Albañileria / Pintura 
    + Adecuacion en baños e impermeab cubierta

*  (2021) Calefaccion y Refrigeracion 
    + Reparación de estufa

*  (2021) Carpinterías 
    + Prov, instalacion de cerraduras x vandal, Prov,coloc cerradura en 6toi x vandalism





## Mobiliario

*  (2023) : Armario 4, Mesa pupitre doble 45, Silla escolar 90 

*  (2022) : Pizarrón 15 

*  (2021) : Banco largo comedor 70, Mesa integradora con escotadura 1, Mesa usos múltiples 35, Pizarrón 3 



