---
title: 'AVDA. SANTA FE 2778'
subtitle: 'INST. DE TIEMPO LIBRE Y RECREACION - LICEO N° 01 JOSE FIGUEROA ALCORTA'
---

#


## Seguridad

*  Espacios seguros: 3 - Estado: Finalizado 
    + Guardia física: NO





## Mobiliario

*  (2022) : Escritorio 4, Mesa pupitre doble 68, Pizarrón 4, Silla escolar 136 

*  (2021) : Escritorio 4, Mesa pupitre doble 60, Pizarrón 6, Silla escolar 124 





## Mantenimiento

*  (2023) Electricidad 
    + Prov y coloc 2 ventiladores para gym., Prov. Coloc sistema de alarma con sensor

*  (2023) Sanitarias 
    + Prov.Coloc inodoro en baño de mujeres

*  (2022) Calefaccion y Refrigeracion 
    + Puesta en normativa de Caldera

*  (2021) Albañileria / Pintura 
    + Puesta en valor de aula 15, 16 y 26, Acondicionar dos aulas para SDF 202

*  (2021) Carpinterías 
    + Cambio de vidrios en 2 aulas 1er piso

*  (2021) Electricidad 
    + Realizar 4 aulas del futuro, Provisión y colocación de un nuevo timbr, Proveer y colocar 14 ventiladores

*  (2021) Incendio 
    + Adecuar IFCI

*  (2021) Sanitarias 
    + Proveer y colocar termotanque-Casero, Reponer tapa de tanque de agua



