---
title: 'TRONADOR 4134 - TRONADOR 4136'
subtitle: 'EEM N° 05/15° - EEM N° 05/15°'
---

#
## Infraestructura

* Reparación de humedad de cimientos, reparación de las mamposterías afectadas y pintura integral. impermeabilización de cubiertas, en sector con filtraciones y respiración de cielorrasos.
Acondicionamiento de baños 
    + mejora edilicia - Planificado 
    + Inicio de obra: Sin fecha de inicio 
    + Plan de obras 2024 - 2027 


* Reparación de humedad de cimientos, reparación de las mamposterías afectadas y pintura integral. impermeabilización de cubiertas, en sector con filtraciones y respiración de cielorrasos. requiere pisos patios
Acondicionamiento de baños 
    + mejora edilicia - Planificado 
    + Inicio de obra: 14/12/2024 
    + Plan de obras 2024 - 2027 






## Mobiliario

*  (2023) : Escritorio 1, Mesa pupitre doble 15, Pizarrón 1, Silla escolar 31 

*  (2022) : Escritorio 1, Mesa pupitre doble 15, Pizarrón 1, Silla escolar 31 

*  (2021) : Escritorio 1, Mesa pupitre doble 15, Pizarrón 1, Silla escolar 31 



