---
title: 'AVDA. LARRAZABAL 5130 - AVDA. LARRAZABAL 5140'
subtitle: 'JII Nº 10 DE 21 - EEM N° 06/21° E.REINGRESO - PI LARRAZABAL - EPC N° 02 MAESTRO EDUARDO LUIS VICENTE - CAIYJ CLUB DE JOVENES LUGANO I y II - CAIYJ CLUB LOLA MORA - ESC. DE COM. N° 35 LEOPOLDO MARECHAL'
---

#
## Infraestructura

* 2do año 
    + SDF - Finalizado 
    + Inicio de obra:10/01/2023 






## Mantenimiento

*  (2023) Incendio 
    + Cambio central de instalación incendio

*  (2022) Albañileria / Pintura 
    + Secundarias del Futuro, Pintura de Paredes, Cambio de solados en pasillos

*  (2022) Carpinterías 
    + Acondicionar dos aulas, Cambio de 4 cerraduras por vandalismo, Cambio de puerta vandalizada, Cambio de cerraduras  por vandalismo, Blackout para sala Espacio Digital

*  (2022) Electricidad 
    + Cambio de timbre casera, Cableado interno artefactos iluminacion

*  (2022) Gas 
    + Cambio  reguladores gas, Habilitación de caldera de calefacción

*  (2022) Incendio 
    + Cambio de central IFCI

*  (2021) Albañileria / Pintura 
    + Colocacion cerámicos sueltos

*  (2021) Calefaccion y Refrigeracion 
    + Cambio de Caldera

*  (2021) Carpinterías 
    + Reparación de rejas perimetrales se devu, Reposicion de cerraduras x vandalismo., cambio de cerradura por vandalismo

*  (2021) Electricidad 
    + Cambio de 2 ventiladores, Cambio de ventiladores por problema de t

*  (2021) Medios de elevación 
    + arreglo por desprevisto eléctrico en mot





## Mobiliario

*  (2023) : Escritorio 3, Mesa pupitre doble 45, Pizarrón 3, Silla escolar 93 

*  (2022) : Escritorio 3, Mesa pupitre doble 45, Pizarrón 3, Silla escolar 93 



