---
title: 'ECUADOR 1158'
subtitle: 'COLEGIO N° 06 MANUEL BELGRANO - COLEGIO N° 15 REVOLUCION DE MAYO'
---

#
## Infraestructura

* 3er año 
    + sdf - Finalizado 
    + Finalizada el 4/4/2023 






## Mantenimiento

*  (2023) Albañileria / Pintura 
    + Prov. coloc placas antihumedad, Impermeabilización azotea y cielorraso H

*  (2023) Carpinterías 
    + Proteccion metalica en balcones y escale

*  (2023) Electricidad 
    + Prov. Coloc sistema de alarmas rectoria

*  (2023) Gas 
    + Adecuación de la Instalación de Gas

*  (2023) Sanitarias 
    + Prov y coloc inodoro en baño de varones, Cambio bomba inmersión + red palomas

*  (2022) Albañileria / Pintura 
    + Pintura en SUM

*  (2022) Carpinterías 
    + colocación de dos ventanas sala de idiom

*  (2022) Electricidad 
    + Adecuaciones en la instalación eléctrica

*  (2022) Gas 
    + Adecuaciones Instalacion Gas

*  (2021) Albañileria / Pintura 
    + Adec Subsuelo+taller cocina+laboratorio

*  (2021) Carpinterías 
    + Prov. coloc reja en desagües de cochera

*  (2021) Sanitarias 
    + Prov. coloc bomba de achique en subsuelo





## Mobiliario

*  (2023) : Escritorio 4, Mesa pupitre doble 60, Pizarrón 4, Silla escolar 124 

*  (2022) : Escritorio 4, Mesa pupitre doble 60, Pizarrón 4, Silla escolar 124 

*  (2021) : Escritorio 6, Mesa pupitre doble 90, Pizarrón 6, Silla escolar 186 





## Seguridad

*  Espacios seguros: 1 - Estado: Finalizado 
    + Guardia física: NO



