---
title: 'AVDA. DEL LIBERTADOR 8635'
subtitle: 'ESC. TEC.S RAGGIO'
---

#
## Infraestructura

* Sanitarios. (fondos covid) 
    + mejora edilicia - Finalizado 
    + Finalizada el 15/1/2023 


* Accesibilidad: ejecución de ascensor y sala de maquina (exterior), adecuación de rampa existente y adecuación de sanitario pcd existente. instalacion electrica completa. istalacion pluvial en campo de depoertes para que no se inunde sector de canchas lugones.mejora edilicia: pintura de aulas de pb del edificio nuevo (pisos superiores dgmesc), revoque y pintura en circulación de edificio histórico pb y 1er piso. revoque, pintura y solados en circulación entre talleres. mejoras de marcos de carpinterías.
Reja de seguridad con concertina superior en fuelle entre el pasadizo de ascensor y edificio existente. (para evitar que alguien ingrese por libertador y se esconda en ese espacio)
Reja de seguridad corrediza para proteger sector de bicicletas. (se retira reja deteriorada con ubicación actual para generar el playón de acceso al ascensor)
Mejoras en escalera exterior en taller de informática en área del fondo.( necesita pasamanos adecuados en ambos laterales, pintura de solado y reemplazo de cintas antideslizantes, ya que se han tropezado alumnos según se nos informó).
Ampliación de taller de carpintería (ee timm), nueva aula en primer piso del taller.
 
    + mejora edilicia - En Proyecto 
    + Inicio de obra: 04/03/2024 






## Mantenimiento

*  (2023) Albañileria / Pintura 
    + Acondicionamiento aulas 25 y 26 para SDF, Acondicionamiento aulas 27 y 28 para SDF, Acondicionamiento aulas 29 y 30 para SDF, Acondicionamiento Secundarias del Futuro

*  (2023) Electricidad 
    + Prov, coloc ventiladores aulas SDF 1ºP, Prov, coloc ventiladores aulas SDF 2ºP, Prov,coloc extractor p/conducto de campa

*  (2023) Saneamiento 
    + Retiro de panal parque de deportes.

*  (2022) Albañileria / Pintura 
    + Acondicionamiento circulación cierlorras, Acondicionamiento aulas para SDF 22,21, Acondicionamiento aulas para SDF 24,23

*  (2022) Otros Servicios 
    + Adecuacion sistema de elevacion mastil





## Mobiliario

*  (2023) : Escritorio 20, Mesa pupitre doble 300, Pizarrón 20, Silla escolar 620 





## Seguridad

*  Espacios seguros: 3 - Estado: A ejecutar 
    + Guardia física: SI



