---
title: 'LASCANO 4044'
subtitle: 'JIC N° 04/18° - IFTS N° 16 SEDE - EPC N° 09 PROVINCIA DE MISIONES'
---

#
## Infraestructura

* Adecuacion de patios, arreglo de muros, istalacion de gas y electrica, sanitarios, accesibilidad basica y pintura 
    + Mejora Edilicia - Planificado 
    + Inicio de obra: NA 






## Mantenimiento

*  (2023) Albañileria / Pintura 
    + Reparacion  revoques y pintura de friso

*  (2023) Electricidad 
    + Proveer ventiladores-Modif inst S Video

*  (2023) Gas 
    + Reemplazo de estufas en aulas

*  (2022) Electricidad 
    + Colocar 3 ventiladores y tomas

*  (2022) Sanitarias 
    + Receptáculo de B° Casera y cocina

*  (2021) Albañileria / Pintura 
    + Trabajos albañileria-Coloc cocina. Se so, Reparar pared divisoria S.Inform y aula.

*  (2021) Carpinterías 
    + Cubierta-Carpinterias-Portero electrico.

*  (2021) Electricidad 
    + provision y colocación de 5 ventiladore

*  (2021) Gas 
    + Puesta a norma instalacion de gas. Cual





## Mobiliario

*  (2021) : Banco largo comedor 6, Mesa usos múltiples 3 



