---
title: 'LAVALLE 2366'
subtitle: 'JIN B (EPCJC 10/01°) - EPC N° 10 PRESIDENTE MANUEL QUINTANA - EPA N° 10 PRESIDENTE MANUEL QUINTANA'
---

#
## Infraestructura

* Impermeabilización en el patio descubierto y el local sanitario de 1° piso y el reemplazo de los desagües
Cloacales en el sector; el mejoramiento sanitarios de alumnos/as presentes; ejecución de rampas que salven diversos desniveles existentes en la planta baja;  pintura y revoques en diversos locales interiores (espacios áulicos y circulaciones)
Mejoramiento integral de los patios descubiertos del edificio. Instalación eléctrica de baja tensión y de muy baja tensión. 
    + Mejora Edilicia - En Obra 
    + Inicio de obra: 20/1/2023 - Avance: 67% - Plazo: 210 días 






## Mantenimiento

*  (2023) Albañileria / Pintura 
    + Adecuacion de instalacion de gas

*  (2022) Electricidad 
    + Iluminacion de  Emergencia

*  (2022) Medios de elevación 
    + Reparar montacargas

*  (2022) Sanitarias 
    + Reemplazo de caño pluvial

*  (2021) Electricidad 
    + Colocación de purificadores

*  (2021) Medios de elevación 
    + Reparar plataformas elevadoras





## Mobiliario

*  (2022) : Armario 9, Escritorio 7, Mesa inicial 8, Mesa pupitre doble 78, Pizarrón 20, Silla escolar 221 



