---
title: 'LACARRA 1151 Y AVDA. FRANCISCO BILBAO'
subtitle: 'EEM N° 02/13°'
---

#
## Infraestructura

* Fachadas exteriores (desprendimiento de pintura y revoques), humedad en subsuelo y levantamiento de solado, aulas en mal estado (placas de cielorraso faltantes, pinturas con grafitis), patio cubierto con filtración por cubierta de vidrio. baños: filtración, faltante de cerámicos y artefactos de luz. pintura en general. 
    + mejora edilicia - En Proyecto 
    + Inicio de obra: 15/02/2024 


* Fachadas exteriores (desprendimiento de pintura y revoques), humedad en subsuelo y levantamiento de solado, aulas en mal estado (placas de cielorraso faltantes, pinturas con grafitis), patio cubierto con filtración por cubierta de vidrio. baños: filtración, faltante de cerámicos y artefactos de luz. pintura en general. 
    + mejora edilicia - Licitación 
    + Inicio de obra: - 


* 2do año 
    + sdf - Finalizado 
    + Finalizada el 16/3/2023 






## Mantenimiento

*  (2023) Albañileria / Pintura 
    + Acondicionamiento de 2 aulas, Realizar 2 cielorrasos en aulas

*  (2023) Gas 
    + Reparar perdida en cañería exterior

*  (2022) Albañileria / Pintura 
    + Realizar protección-Fachada

*  (2022) Electricidad 
    + Realizar 2 aulas del futuro

*  (2022) Gas 
    + Arreglo de instalación de gas artefactos

*  (2021) Albañileria / Pintura 
    + Reponer revestimientos faltantes Items 1, Reparar baño vandalizado, Cateo en cornisa de fachada

*  (2021) Carpinterías 
    + Reponer vidrios y reja





## Mobiliario

*  (2023) : Escritorio 2, Mesa pupitre doble 30, Pizarrón 2, Silla escolar 62, NA 1 

*  (2022) : Escritorio 2, Mesa pupitre doble 30, Pizarrón 2, Silla escolar 62 



