---
title: 'LETONIA 26'
subtitle: 'EPC N° 25 BANDERA ARGENTINA'
---

#


## Seguridad

*  Espacios seguros: 0 - Estado: A confirmar 
    + Guardia física: SI





## Mobiliario

*  (2023) : Banco largo comedor 24, Mesa usos múltiples 12, NA 1 

*  (2021) : Armario 1, Banco largo comedor 50, Mesa pupitre doble 30, Mesa usos múltiples 25, Silla escolar 64 





## Mantenimiento

*  (2023) Calefaccion y Refrigeracion 
    + Colocacion de aires acondicionados

*  (2023) Electricidad 
    + Reemplazo de Ventiladores, Reposicion de luminarias

*  (2022) Carpinterías 
    + Provision y Colocacion de Black out-ofic, Provision y colocacion de Black out-espa

*  (2022) Incendio 
    + Rep. de Extintores y Acc. de la IFCI

*  (2022) Sanitarias 
    + Reposicion de inodoros vandalizados

*  (2021) Calefaccion y Refrigeracion 
    + ADECUACION SIST CALEFACCION

*  (2021) Incendio 
    + PROVISION Y COLOCACION DE BLACKOUT

*  (2021) Medios de elevación 
    + Reparacion y puesta en marcha ascensores

*  (2021) Sanitarias 
    + Conexion de agua a cisternas, Proveer camion cisterna de agua potable



