---
title: 'ZUVIRIA 6544 - ZUVIRIA 6550'
subtitle: 'ESCUELA INF. N° 08/20° - JII N° 04/20° - EEM N° 01/20° BIB.CONGRESO DE LA NACION'
---

#
## Infraestructura

* 3er año 
    + sdf - Finalizado 
    + Finalizada el - 


* Tanque de bombeo, bombas (fondos covid) 
    + mejora edilicia - Finalizado 
    + Finalizada el 11/4/2022 






## Mantenimiento

*  (2023) Electricidad 
    + Prov, coloc 4 reflectores LED 100 watt, Colocacion de sistema de seguridad, Robo del timbre de acesso al colegio

*  (2022) Calefaccion y Refrigeracion 
    + Conexión de 6 estufas ecosol en aulas

*  (2022) Carpinterías 
    + Cambio de vidrio ventana por vandalismo

*  (2022) Sanitarias 
    + Cambio bacha cocina

*  (2021) Carpinterías 
    + Guias nuevas de persianas metalicas x va, Cambio de cerradura puerta entrada x van, Cambio de 2 vidrios en sum, Rejas para patio-sector puertas, Colocacion de parante metalico

*  (2021) Electricidad 
    + Colocacion de tomas corriente lactario

*  (2021) Sanitarias 
    + Coloc bomba con tablero c/automatico





## Mobiliario

*  (2023) : Banco largo comedor 38, Escritorio 2, Mesa pupitre doble 30, Mesa usos múltiples 19, Pizarrón 2, Silla escolar 84 

*  (2022) : Escritorio 3, Mesa pupitre doble 45, Pizarrón 3, Silla escolar 93 

*  (2021) : Escritorio 3, Mesa pupitre doble 45, Pizarrón 3, Silla escolar 93 





## Seguridad

*  Espacios seguros: 1 - Estado: Suspendida ejecución 
    + Guardia física: SI



