---
title: 'POLA Y JOSE BARROS PAZOS 5250'
subtitle: 'CENOF POLA - EPC N° 19 HERMANOS LATINOAMERICANOS - EEM N° 01/21° - ESCUELA INF. N° 08/21°'
---

#


## Seguridad

*  Espacios seguros: 0 - Estado: Colocada a configurar 
    + Guardia física: NO

*  Espacios seguros: 3 - Estado: Colocada a configurar 
    + Guardia física: NO

*  Espacios seguros: 0 - Estado: Colocada a configurar 
    + Guardia física: NO





## Mobiliario

*  (2023) : Escritorio 1, Mesa pupitre doble 15, Pizarrón 1, Silla escolar 31 

*  (2022) : Escritorio 3, Mesa pupitre doble 45, Pizarrón 3, Silla escolar 93 

*  (2021) : Armario 4, Banco largo comedor 64, Escritorio 7, Mesa inicial 5, Mesa pupitre doble 105, Mesa usos múltiples 32, Pizarrón 4, Silla escolar 247 





## Mantenimiento

*  (2023) Albañileria / Pintura 
    + Realización de tabiques divisorios

*  (2023) Electricidad 
    + Colocacion de alarma y camaras, Reposicion ventilador y toma corriente, Reposición1 ventilador de techo aula, Cambio de ventilador en aula

*  (2023) Medios de elevación 
    + Puesta en marcha ascensor por vandalismo

*  (2022) Albañileria / Pintura 
    + adecuacion aula sdf, Mamposteria de ladrillo

*  (2022) Carpinterías 
    + Colocacion de flim de color para aula

*  (2022) Electricidad 
    + Alimentación electrica en huerta

*  (2022) Incendio 
    + cambio 3 tapas de incendio via publica

*  (2021) Albañileria / Pintura 
    + Adecuación de 3 aulas SDF

*  (2021) Carpinterías 
    + cerradura baño discapacitado, Cerradura vandalizada  en exterior

*  (2021) Electricidad 
    + Colocar caja metalica p/protejer alarma, Cambio luminarias led comedor

*  (2021) Medios de elevación 
    + Corte de fuerza motriz de ascensor, Corte de fuerza motriz de ascensor



