---
title: 'AVDA. CRISOLOGO LARRALDE 5085'
subtitle: 'ESC. TEC. N° 36 ALTE. GUILLERMO BROWN - ESC. SUPERIOR DE EDUCACIÓN ARTÍSTICA EN MÚSICA JUAN PEDRO ESNAOLA - ESCUELA INF. N° 06/15° NARANJO EN FLOR - ESC. PARA NIÑOS, NIÑAS Y JÓVENES CON PLURIDISCAPACIDAD MOTORA N° 11 DR. AQUILES GAREISO - ESC. INTEGRAL INTERDISCIPLINARIA N° 01 - Auditorio Polo Saavedra - Sup Inicial X B'
---

#
## Infraestructura

* Terminación vestuarios, pileta, sanitarios, estacionamiento, parquizado 
    + Mejora Edilicia - En Obra 
    + Inicio de obra: 20/1/2023 - Avance: 26% - Fecha de finalización: 30/12/2023 


* 3er año 
    + SDF - Finalizado 
    + Finalizada el 11/3/2023 






## Mantenimiento

*  (2023) Calefaccion y Refrigeracion 
    + Instalación de dos equipos de AA, colocacion/reparacion de blackout

*  (2023) Carpinterías 
    + Cambio de vidrios vandalizados, Reemplazo de espejo y vidrios rotos, Reparación equipos calefacción, Colocación de parasoles

*  (2023) Electricidad 
    + Instalación de portero eléctrico, Reparación de ventiladores, Colocación de luces LED, Instalación en espacios seguros., Instalación luces led, Colocación de ventiladores de pared

*  (2023) Incendio 
    + Reemplazo de sensor en taller

*  (2023) Sanitarias 
    + Cambio de tanques cisterna

*  (2022) Albañileria / Pintura 
    + Refuncionalización espacio bibliot. y pr, Realizar division y pintura sala, Pintura de aulas, Pintura  de circulaciones

*  (2022) Calefaccion y Refrigeracion 
    + Nuevos desagües de equipos de A°A°, Reparar Aire Acondicionado central

*  (2022) Carpinterías 
    + Divisor de aula Nro 2, SUM- Reemplazo de paños fijos por ventan, Comedor- Reemplazo de paños fijos por ve, Proveer rampa en sanitario, Reemplazar vidrio vandalizado en SS, Prov. y coloc. espejos aula 6, Refuerzo cerco perimetral canchas, Refuerzo cerco perimetral, Proveer rampa en Baño-Posprimaria, Reparación de puertas PB+2ndo piso, Reemplazar vidrio puerta salida, Reemplazar vidrio enfermería, Reposición de vidrios vandalizados, Vidrios vandalizados, Reparación  puerta violentada y portero, Restauracion de anfiteatro abierto

*  (2022) Cubiertas / Impermeabilizaciones 
    + Impermeabilización y realización drenaje

*  (2022) Electricidad 
    + Provisión de nuevos artefactos LED, Reemplazo iluminacion led PB + 2º piso, Instalación de artefactos LED, Reemplazo iluminación LED 1° piso, Instalación eléctrica de extractores, Reemplazo de capacitores del TGBT

*  (2022) Gas 
    + Adecuación de la red a normativa vigente

*  (2022) Incendio 
    + Reemplazo de tapas y lanzas vandalizadas

*  (2022) Medios de elevación 
    + Reparación de puertas vandalizadas, Reparación del ascensor N5

*  (2022) Sanitarias 
    + Reemplazo de grifería, Reemplazo de griferías, Cambio de válvulas de inodoro

*  (2021) Albañileria / Pintura 
    + obra civil cámara nueva, Cerramientos- oficinas nuevas, SdF 2022- dos aulas, Ejecución de rampa exterior, Provisión y coloc de mástil- patio

*  (2021) Calefaccion y Refrigeracion 
    + Refrigeración depósito-Cámara frigorific

*  (2021) Carpinterías 
    + Reemplazo vidrios laminados 3+3-Taller y, Provisión pasamanos faltantes en Posprim, Reemplazo de ventana en Secretaría, Reemplazar ventanas de taller, Ejecución de bajo mesadas, Provisión de pasamanos

*  (2021) Electricidad 
    + cambio de interruptor y UPS media tensió, Reemplazo de reflectores exteriores, Adecuación de tablero de AA, Independización de tableros eléctricos, reemplazo comando motor interruptor TP, SdF 2022- aula adicional, Reemplazo artefactos iluminacion patio s, Reemplazo de reflectores en patio SS

*  (2021) Incendio 
    + Ampliar sist de detección de incendio, Reemplazo de manguera y baterias, Reemplazo de manguera de incendio, Reemplazo de manguera de incendio, reposición 4 detectores temperat-Acceso, nueva central de incendio adicional

*  (2021) Medios de elevación 
    + Reparar ascensor, Reparar ascensores

*  (2021) Otros Servicios 
    + Limpieza estructura pileta

*  (2021) Sanitarias 
    + Reemplazo de mingitorio vandalizado, Reforma sanitario, Nueva inst de bombeo en reservorio





## Mobiliario

*  (2023) : Escritorio 2, Locker 15, Mesa pupitre doble 30, Pizarrón 2, Silla escolar 62 

*  (2022) : Escritorio 6, Mesa pupitre doble 90, Pizarrón 6, Silla escolar 186 

*  (2021) : Escritorio 6, Mesa pupitre doble 90, Pizarrón 6, Silla escolar 186, Varios 70 





## Seguridad

*  Espacios seguros: 0 - Estado: Finalizado 
    + Guardia física: SI

*  Espacios seguros: 0 - Estado: Finalizado 
    + Guardia física: NO

*  Espacios seguros: 2 - Estado: Finalizado 
    + Guardia física: SI

*  Espacios seguros: 0 - Estado: Finalizado 
    + Guardia física: SI



