---
title: 'DR. PEDRO I. RIVERA 4221'
subtitle: 'ESCUELA INF. N° 08/15° - EPC N° 24 FRANCISCO MORAZAN - INST. SUPERIOR DEL PROF. DE EDUCACIÓN ESPECIAL'
---

#


## Seguridad

*  Espacios seguros: 0 - Estado: A confirmar 
    + Guardia física: SI

*  Espacios seguros: 0 - Estado: A confirmar 
    + Guardia física: SI

*  Espacios seguros: 1 - Estado: A confirmar 
    + Guardia física: SI





## Mobiliario

*  (2023) : Piso antigolpe para juegos 60 

*  (2021) : Banco largo comedor 14, Mesa usos múltiples 7 





## Mantenimiento

*  (2023) Albañileria / Pintura 
    + Pintura de circulaciones, Pintura de aulas y pasillos, Modificación de baños, Puesta a punto del edificio, Pintura interior de aulas, Reemplazo paneles vinilicos vandalizados, Mantenimiento equipo BMS

*  (2023) Calefaccion y Refrigeracion 
    + Reparación de equipo vrv

*  (2023) Carpinterías 
    + reparación de carpinterias de aluminio, Colocación de red antipalomas

*  (2023) Electricidad 
    + Reparación del sistema de ventilación, Reparación del sistema de datos, Mantención del equipo BMS, Colocación de paneles LED

*  (2023) Sanitarias 
    + Colocación de válvula interceptora, Reemplazo de bombas de circulacion

*  (2022) Albañileria / Pintura 
    + Ejecución de tabique antihumedad SUM, Acondicionamiento de medianera patio

*  (2022) Calefaccion y Refrigeracion 
    + instalación de un equipo de A°A°, Reparación de equipo vrv

*  (2022) Electricidad 
    + Reparación de grupo electrógeno

*  (2022) Incendio 
    + Prov. matafuegos y reparación IFCI

*  (2022) Sanitarias 
    + Mantenimiento del predio S. XXI, Modificación de colector tanques agua, Reparación de termotanques solares, Limpieza de tanques adicional

*  (2021) Albañileria / Pintura 
    + Acond acustico taller de radio

*  (2021) Carpinterías 
    + Prov,coloc puerta reja en cocina, Reparar reja plegable acceso, Extension reja exterior PB a gimnasio, Provisión de mosquiteros cocina

*  (2021) Otros Servicios 
    + Sist riego balcón 3er piso frente, Sist riego canteros azotea, Acond. y nivelacion cantero PB



