---
title: 'AVDA. JUAN BAUTISTA ALBERDI 4139'
subtitle: 'ESC. SUPERIOR DE EDUCACIÓN ARTÍSTICA EN ARTES VISUALES ROGELIO YRURTIA - EPC N° 23'
---

#
## Infraestructura

* 3er año 
    + En Obra - SDF 


## Mobiliario

*  (2023) : Locker 15 

*  (2022) : Escritorio 4, Mesa pupitre doble 15, Pizarrón 4, Silla escolar 140 

*  (2021) : Banco largo comedor 40, Mesa usos múltiples 30 





## Mantenimiento

*  (2023) Sanitarias 
    + Reemplazo de Griferias vandalizadas, Reemplazar 2 bombas cloacales

*  (2022) Carpinterías 
    + Reponer 4 cerraduras rotas, Ejecutar e instalar puerta reja, Proveer y colocar rejas de seguridad. Mo, Protecciones 24 ventanas de gimnasio

*  (2022) Medios de elevación 
    + Reparar ascensor 1 vandalizado, Colocacion de cerraduras en ascensores

*  (2022) Sanitarias 
    + Camara cloacal complementaria, Modificación  de los desagües

*  (2021) Carpinterías 
    + Reparar 15 cerraduras de aulas Se solici

*  (2021) Electricidad 
    + reempl artefactos led quemados pasillo

*  (2021) Sanitarias 
    + reponer tapa de tanque de reserva, Adecuar decantadores metálicos móviles





* Trabajos en  medianeras, subsuelo por filtraciones 
    + Finalizado - Mejora Edilicia 




